/*
 * Trading API
 * Alpaca's Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package markets.alpaca.client.openapi.trading.api;

import markets.alpaca.client.openapi.trading.http.ApiCallback;
import markets.alpaca.client.openapi.trading.http.ApiClient;
import markets.alpaca.client.openapi.trading.http.ApiException;
import markets.alpaca.client.openapi.trading.http.ApiResponse;
import markets.alpaca.client.openapi.trading.http.Configuration;
import markets.alpaca.client.openapi.trading.http.Pair;
import markets.alpaca.client.openapi.trading.http.ProgressRequestBody;
import markets.alpaca.client.openapi.trading.http.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import markets.alpaca.client.openapi.trading.model.CreateCryptoTransferRequest;
import markets.alpaca.client.openapi.trading.model.CreateWhitelistedAddressRequest;
import markets.alpaca.client.openapi.trading.model.CryptoChain;
import markets.alpaca.client.openapi.trading.model.CryptoTransfer;
import markets.alpaca.client.openapi.trading.model.CryptoWallet;
import markets.alpaca.client.openapi.trading.model.WalletFeeEstimateResponse;
import markets.alpaca.client.openapi.trading.model.WhitelistedAddress;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated client for CryptoFundingApi operations.
 *
 * <p>This class is generated from the configured OpenAPI spec. Operation method Javadocs include
 * OAS summaries, descriptions, parameters, return types, response details, and external
 * documentation links when present in the spec.
 *
 * <h2>Operations</h2>
 *
 * <ul>
 * 
 *   <li><b>{@code createCryptoTransferForAccount}</b>: Request a New Withdrawal</li>
 * 
 *   <li><b>{@code createWhitelistedAddress}</b>: Request a new whitelisted address</li>
 * 
 *   <li><b>{@code deleteWhitelistedAddress}</b>: Delete a whitelisted address</li>
 * 
 *   <li><b>{@code getCryptoFundingTransfer}</b>: Retrieve a Crypto Funding Transfer</li>
 * 
 *   <li><b>{@code getCryptoTransferEstimate}</b>: Returns the estimated gas fee for a proposed transaction.</li>
 * 
 *   <li><b>{@code listCryptoFundingTransfers}</b>: Retrieve Crypto Funding Transfers</li>
 * 
 *   <li><b>{@code listCryptoFundingWallets}</b>: Retrieve Crypto Funding Wallets</li>
 * 
 *   <li><b>{@code listWhitelistedAddress}</b>: An array of whitelisted addresses</li>
 * 
 * </ul>
 */
public class CryptoFundingApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public CryptoFundingApi() {
        this(Configuration.getDefaultApiClient());
    }

    public CryptoFundingApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createCryptoTransferForAccount
     * @param createCryptoTransferRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully requested a transfer. </td><td>  -  </td></tr>
     </table>
     * @deprecated
     */
    @Deprecated
    public okhttp3.Call createCryptoTransferForAccountCall(@javax.annotation.Nonnull CreateCryptoTransferRequest createCryptoTransferRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createCryptoTransferRequest;

        // create path and map variables
        String localVarPath = "/v2/wallets/transfers";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "API_Key", "API_Secret" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @Deprecated
    @SuppressWarnings("rawtypes")
    private okhttp3.Call createCryptoTransferForAccountValidateBeforeCall(@javax.annotation.Nonnull CreateCryptoTransferRequest createCryptoTransferRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'createCryptoTransferRequest' is set
        if (createCryptoTransferRequest == null) {
            throw new ApiException("Missing the required parameter 'createCryptoTransferRequest' when calling createCryptoTransferForAccount(Async)");
        }

        return createCryptoTransferForAccountCall(createCryptoTransferRequest, _callback);

    }

    /**
     * Request a New Withdrawal
     * Creates a withdrawal request. Note that outgoing withdrawals must be sent to a whitelisted address and you must whitelist addresses at least 24 hours in advance. If you attempt to withdraw funds to a non-whitelisted address then the transfer will be rejected.
     * @param createCryptoTransferRequest  (required)
     * @return CryptoTransfer
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully requested a transfer. </td><td>  -  </td></tr>
     </table>
     * @deprecated
     */
    @Deprecated
    public CryptoTransfer createCryptoTransferForAccount(@javax.annotation.Nonnull CreateCryptoTransferRequest createCryptoTransferRequest) throws ApiException {
        ApiResponse<CryptoTransfer> localVarResp = createCryptoTransferForAccountWithHttpInfo(createCryptoTransferRequest);
        return localVarResp.getData();
    }

    /**
     * Request a New Withdrawal
     * Creates a withdrawal request. Note that outgoing withdrawals must be sent to a whitelisted address and you must whitelist addresses at least 24 hours in advance. If you attempt to withdraw funds to a non-whitelisted address then the transfer will be rejected.
     * @param createCryptoTransferRequest  (required)
     * @return ApiResponse&lt;CryptoTransfer&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully requested a transfer. </td><td>  -  </td></tr>
     </table>
     * @deprecated
     */
    @Deprecated
    public ApiResponse<CryptoTransfer> createCryptoTransferForAccountWithHttpInfo(@javax.annotation.Nonnull CreateCryptoTransferRequest createCryptoTransferRequest) throws ApiException {
        okhttp3.Call localVarCall = createCryptoTransferForAccountValidateBeforeCall(createCryptoTransferRequest, null);
        Type localVarReturnType = new TypeToken<CryptoTransfer>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Request a New Withdrawal (asynchronously)
     * Creates a withdrawal request. Note that outgoing withdrawals must be sent to a whitelisted address and you must whitelist addresses at least 24 hours in advance. If you attempt to withdraw funds to a non-whitelisted address then the transfer will be rejected.
     * @param createCryptoTransferRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully requested a transfer. </td><td>  -  </td></tr>
     </table>
     * @deprecated
     */
    @Deprecated
    public okhttp3.Call createCryptoTransferForAccountAsync(@javax.annotation.Nonnull CreateCryptoTransferRequest createCryptoTransferRequest, final ApiCallback<CryptoTransfer> _callback) throws ApiException {

        okhttp3.Call localVarCall = createCryptoTransferForAccountValidateBeforeCall(createCryptoTransferRequest, _callback);
        Type localVarReturnType = new TypeToken<CryptoTransfer>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for createWhitelistedAddress
     * @param createWhitelistedAddressRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully requested a whitelisted address </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createWhitelistedAddressCall(@javax.annotation.Nonnull CreateWhitelistedAddressRequest createWhitelistedAddressRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createWhitelistedAddressRequest;

        // create path and map variables
        String localVarPath = "/v2/wallets/whitelists";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "API_Key", "API_Secret" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createWhitelistedAddressValidateBeforeCall(@javax.annotation.Nonnull CreateWhitelistedAddressRequest createWhitelistedAddressRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'createWhitelistedAddressRequest' is set
        if (createWhitelistedAddressRequest == null) {
            throw new ApiException("Missing the required parameter 'createWhitelistedAddressRequest' when calling createWhitelistedAddress(Async)");
        }

        return createWhitelistedAddressCall(createWhitelistedAddressRequest, _callback);

    }

    /**
     * Request a new whitelisted address
     * Submits a new whitelisted withdrawal address for your account. The chain is derived from the supplied asset symbol and address, and the same address cannot be whitelisted twice on the same chain.  Where travel rule reporting applies to your account, address details are validated against the travel rule provider before being persisted.  Note that whitelisted addresses must wait at least 24 hours before they can be used as a withdrawal destination.
     * @param createWhitelistedAddressRequest  (required)
     * @return WhitelistedAddress
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully requested a whitelisted address </td><td>  -  </td></tr>
     </table>
     */
    public WhitelistedAddress createWhitelistedAddress(@javax.annotation.Nonnull CreateWhitelistedAddressRequest createWhitelistedAddressRequest) throws ApiException {
        ApiResponse<WhitelistedAddress> localVarResp = createWhitelistedAddressWithHttpInfo(createWhitelistedAddressRequest);
        return localVarResp.getData();
    }

    /**
     * Request a new whitelisted address
     * Submits a new whitelisted withdrawal address for your account. The chain is derived from the supplied asset symbol and address, and the same address cannot be whitelisted twice on the same chain.  Where travel rule reporting applies to your account, address details are validated against the travel rule provider before being persisted.  Note that whitelisted addresses must wait at least 24 hours before they can be used as a withdrawal destination.
     * @param createWhitelistedAddressRequest  (required)
     * @return ApiResponse&lt;WhitelistedAddress&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully requested a whitelisted address </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<WhitelistedAddress> createWhitelistedAddressWithHttpInfo(@javax.annotation.Nonnull CreateWhitelistedAddressRequest createWhitelistedAddressRequest) throws ApiException {
        okhttp3.Call localVarCall = createWhitelistedAddressValidateBeforeCall(createWhitelistedAddressRequest, null);
        Type localVarReturnType = new TypeToken<WhitelistedAddress>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Request a new whitelisted address (asynchronously)
     * Submits a new whitelisted withdrawal address for your account. The chain is derived from the supplied asset symbol and address, and the same address cannot be whitelisted twice on the same chain.  Where travel rule reporting applies to your account, address details are validated against the travel rule provider before being persisted.  Note that whitelisted addresses must wait at least 24 hours before they can be used as a withdrawal destination.
     * @param createWhitelistedAddressRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully requested a whitelisted address </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createWhitelistedAddressAsync(@javax.annotation.Nonnull CreateWhitelistedAddressRequest createWhitelistedAddressRequest, final ApiCallback<WhitelistedAddress> _callback) throws ApiException {

        okhttp3.Call localVarCall = createWhitelistedAddressValidateBeforeCall(createWhitelistedAddressRequest, _callback);
        Type localVarReturnType = new TypeToken<WhitelistedAddress>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteWhitelistedAddress
     * @param whitelistedAddressId The whitelisted address to delete (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully deleted a whitelisted address </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteWhitelistedAddressCall(@javax.annotation.Nonnull String whitelistedAddressId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/wallets/whitelists/{whitelisted_address_id}"
            .replace("{" + "whitelisted_address_id" + "}", localVarApiClient.escapeString(whitelistedAddressId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "API_Key", "API_Secret" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteWhitelistedAddressValidateBeforeCall(@javax.annotation.Nonnull String whitelistedAddressId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'whitelistedAddressId' is set
        if (whitelistedAddressId == null) {
            throw new ApiException("Missing the required parameter 'whitelistedAddressId' when calling deleteWhitelistedAddress(Async)");
        }

        return deleteWhitelistedAddressCall(whitelistedAddressId, _callback);

    }

    /**
     * Delete a whitelisted address
     * Deletes a whitelisted withdrawal address by ID. Subsequent withdrawals targeting the deleted address will be rejected.
     * @param whitelistedAddressId The whitelisted address to delete (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully deleted a whitelisted address </td><td>  -  </td></tr>
     </table>
     */
    public void deleteWhitelistedAddress(@javax.annotation.Nonnull String whitelistedAddressId) throws ApiException {
        deleteWhitelistedAddressWithHttpInfo(whitelistedAddressId);
    }

    /**
     * Delete a whitelisted address
     * Deletes a whitelisted withdrawal address by ID. Subsequent withdrawals targeting the deleted address will be rejected.
     * @param whitelistedAddressId The whitelisted address to delete (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully deleted a whitelisted address </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> deleteWhitelistedAddressWithHttpInfo(@javax.annotation.Nonnull String whitelistedAddressId) throws ApiException {
        okhttp3.Call localVarCall = deleteWhitelistedAddressValidateBeforeCall(whitelistedAddressId, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Delete a whitelisted address (asynchronously)
     * Deletes a whitelisted withdrawal address by ID. Subsequent withdrawals targeting the deleted address will be rejected.
     * @param whitelistedAddressId The whitelisted address to delete (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully deleted a whitelisted address </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteWhitelistedAddressAsync(@javax.annotation.Nonnull String whitelistedAddressId, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteWhitelistedAddressValidateBeforeCall(whitelistedAddressId, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for getCryptoFundingTransfer
     * @param transferId The crypto transfer to retrieve (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A single crypto transfer object </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCryptoFundingTransferCall(@javax.annotation.Nonnull String transferId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/wallets/transfers/{transfer_id}"
            .replace("{" + "transfer_id" + "}", localVarApiClient.escapeString(transferId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "API_Key", "API_Secret" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getCryptoFundingTransferValidateBeforeCall(@javax.annotation.Nonnull String transferId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'transferId' is set
        if (transferId == null) {
            throw new ApiException("Missing the required parameter 'transferId' when calling getCryptoFundingTransfer(Async)");
        }

        return getCryptoFundingTransferCall(transferId, _callback);

    }

    /**
     * Retrieve a Crypto Funding Transfer
     * Returns a specific wallet transfer by passing into the query the transfer_id.
     * @param transferId The crypto transfer to retrieve (required)
     * @return CryptoTransfer
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A single crypto transfer object </td><td>  -  </td></tr>
     </table>
     */
    public CryptoTransfer getCryptoFundingTransfer(@javax.annotation.Nonnull String transferId) throws ApiException {
        ApiResponse<CryptoTransfer> localVarResp = getCryptoFundingTransferWithHttpInfo(transferId);
        return localVarResp.getData();
    }

    /**
     * Retrieve a Crypto Funding Transfer
     * Returns a specific wallet transfer by passing into the query the transfer_id.
     * @param transferId The crypto transfer to retrieve (required)
     * @return ApiResponse&lt;CryptoTransfer&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A single crypto transfer object </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CryptoTransfer> getCryptoFundingTransferWithHttpInfo(@javax.annotation.Nonnull String transferId) throws ApiException {
        okhttp3.Call localVarCall = getCryptoFundingTransferValidateBeforeCall(transferId, null);
        Type localVarReturnType = new TypeToken<CryptoTransfer>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve a Crypto Funding Transfer (asynchronously)
     * Returns a specific wallet transfer by passing into the query the transfer_id.
     * @param transferId The crypto transfer to retrieve (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A single crypto transfer object </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCryptoFundingTransferAsync(@javax.annotation.Nonnull String transferId, final ApiCallback<CryptoTransfer> _callback) throws ApiException {

        okhttp3.Call localVarCall = getCryptoFundingTransferValidateBeforeCall(transferId, _callback);
        Type localVarReturnType = new TypeToken<CryptoTransfer>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getCryptoTransferEstimate
     * @param asset The asset for the proposed transaction (optional)
     * @param fromAddress The originating address of the proposed transaction (optional)
     * @param toAddress The destination address of the proposed transaction (optional)
     * @param amount The amount, denoted in the specified asset, of the proposed transaction (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCryptoTransferEstimateCall(@javax.annotation.Nullable String asset, @javax.annotation.Nullable String fromAddress, @javax.annotation.Nullable String toAddress, @javax.annotation.Nullable String amount, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/wallets/fees/estimate";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (asset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("asset", asset));
        }

        if (fromAddress != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("from_address", fromAddress));
        }

        if (toAddress != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("to_address", toAddress));
        }

        if (amount != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("amount", amount));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "API_Key", "API_Secret" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getCryptoTransferEstimateValidateBeforeCall(@javax.annotation.Nullable String asset, @javax.annotation.Nullable String fromAddress, @javax.annotation.Nullable String toAddress, @javax.annotation.Nullable String amount, final ApiCallback _callback) throws ApiException {
        return getCryptoTransferEstimateCall(asset, fromAddress, toAddress, amount, _callback);

    }

    /**
     * Returns the estimated gas fee for a proposed transaction.
     * Returns the estimated on-chain network (gas) fee for a proposed crypto withdrawal at current chain conditions. Pass the &#x60;asset&#x60;, &#x60;from_address&#x60;, &#x60;to_address&#x60;, and &#x60;amount&#x60; you intend to send; the response reports the network fee that would be charged for the corresponding transaction.
     * @param asset The asset for the proposed transaction (optional)
     * @param fromAddress The originating address of the proposed transaction (optional)
     * @param toAddress The destination address of the proposed transaction (optional)
     * @param amount The amount, denoted in the specified asset, of the proposed transaction (optional)
     * @return WalletFeeEstimateResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public WalletFeeEstimateResponse getCryptoTransferEstimate(@javax.annotation.Nullable String asset, @javax.annotation.Nullable String fromAddress, @javax.annotation.Nullable String toAddress, @javax.annotation.Nullable String amount) throws ApiException {
        ApiResponse<WalletFeeEstimateResponse> localVarResp = getCryptoTransferEstimateWithHttpInfo(asset, fromAddress, toAddress, amount);
        return localVarResp.getData();
    }

    /**
     * Returns the estimated gas fee for a proposed transaction.
     * Returns the estimated on-chain network (gas) fee for a proposed crypto withdrawal at current chain conditions. Pass the &#x60;asset&#x60;, &#x60;from_address&#x60;, &#x60;to_address&#x60;, and &#x60;amount&#x60; you intend to send; the response reports the network fee that would be charged for the corresponding transaction.
     * @param asset The asset for the proposed transaction (optional)
     * @param fromAddress The originating address of the proposed transaction (optional)
     * @param toAddress The destination address of the proposed transaction (optional)
     * @param amount The amount, denoted in the specified asset, of the proposed transaction (optional)
     * @return ApiResponse&lt;WalletFeeEstimateResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<WalletFeeEstimateResponse> getCryptoTransferEstimateWithHttpInfo(@javax.annotation.Nullable String asset, @javax.annotation.Nullable String fromAddress, @javax.annotation.Nullable String toAddress, @javax.annotation.Nullable String amount) throws ApiException {
        okhttp3.Call localVarCall = getCryptoTransferEstimateValidateBeforeCall(asset, fromAddress, toAddress, amount, null);
        Type localVarReturnType = new TypeToken<WalletFeeEstimateResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Returns the estimated gas fee for a proposed transaction. (asynchronously)
     * Returns the estimated on-chain network (gas) fee for a proposed crypto withdrawal at current chain conditions. Pass the &#x60;asset&#x60;, &#x60;from_address&#x60;, &#x60;to_address&#x60;, and &#x60;amount&#x60; you intend to send; the response reports the network fee that would be charged for the corresponding transaction.
     * @param asset The asset for the proposed transaction (optional)
     * @param fromAddress The originating address of the proposed transaction (optional)
     * @param toAddress The destination address of the proposed transaction (optional)
     * @param amount The amount, denoted in the specified asset, of the proposed transaction (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCryptoTransferEstimateAsync(@javax.annotation.Nullable String asset, @javax.annotation.Nullable String fromAddress, @javax.annotation.Nullable String toAddress, @javax.annotation.Nullable String amount, final ApiCallback<WalletFeeEstimateResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getCryptoTransferEstimateValidateBeforeCall(asset, fromAddress, toAddress, amount, _callback);
        Type localVarReturnType = new TypeToken<WalletFeeEstimateResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listCryptoFundingTransfers
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> An array of transfer objects </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listCryptoFundingTransfersCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/wallets/transfers";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "API_Key", "API_Secret" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listCryptoFundingTransfersValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return listCryptoFundingTransfersCall(_callback);

    }

    /**
     * Retrieve Crypto Funding Transfers
     * Returns an array of all transfers associated with the given account across all wallets.
     * @return CryptoTransfer
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> An array of transfer objects </td><td>  -  </td></tr>
     </table>
     */
    public CryptoTransfer listCryptoFundingTransfers() throws ApiException {
        ApiResponse<CryptoTransfer> localVarResp = listCryptoFundingTransfersWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Retrieve Crypto Funding Transfers
     * Returns an array of all transfers associated with the given account across all wallets.
     * @return ApiResponse&lt;CryptoTransfer&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> An array of transfer objects </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CryptoTransfer> listCryptoFundingTransfersWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = listCryptoFundingTransfersValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<CryptoTransfer>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve Crypto Funding Transfers (asynchronously)
     * Returns an array of all transfers associated with the given account across all wallets.
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> An array of transfer objects </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listCryptoFundingTransfersAsync(final ApiCallback<CryptoTransfer> _callback) throws ApiException {

        okhttp3.Call localVarCall = listCryptoFundingTransfersValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<CryptoTransfer>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listCryptoFundingWallets
     * @param asset Filter by crypto asset symbol, e.g. BTC, ETH, USDT. If specified and no wallet exists, one will be created. (optional)
     * @param chain Optional chain identifier. Use to request wallets for a specific chain when asset is a multi-chain crypto asset. If not specified, network is considered. (optional)
     * @param network Deprecated. Use chain instead. Optional network identifier which is used to request wallets for a specific network when asset is a multi-chain crypto asset. When both &#39;chain&#39; and &#39;network&#39; are specified, &#39;chain&#39; will take precedence and &#39;network&#39; will be ignored. If &#39;chain&#39; and &#39;network&#39; are not specified, the default &#39;network&#39; (ethereum) will be used. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A single wallet object if an asset is specified or an array of wallet objects if no asset is specified </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listCryptoFundingWalletsCall(@javax.annotation.Nullable String asset, @javax.annotation.Nullable CryptoChain chain, @javax.annotation.Nullable String network, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/wallets";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (asset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("asset", asset));
        }

        if (chain != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("chain", chain));
        }

        if (network != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("network", network));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "API_Key", "API_Secret" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listCryptoFundingWalletsValidateBeforeCall(@javax.annotation.Nullable String asset, @javax.annotation.Nullable CryptoChain chain, @javax.annotation.Nullable String network, final ApiCallback _callback) throws ApiException {
        return listCryptoFundingWalletsCall(asset, chain, network, _callback);

    }

    /**
     * Retrieve Crypto Funding Wallets
     * Lists wallets for the account given in the path parameter. If an asset is specified and no wallet for the account and asset pair exists one will be created. If no asset is specified only existing wallets will be listed for the account. An account may have at most one wallet per asset.
     * @param asset Filter by crypto asset symbol, e.g. BTC, ETH, USDT. If specified and no wallet exists, one will be created. (optional)
     * @param chain Optional chain identifier. Use to request wallets for a specific chain when asset is a multi-chain crypto asset. If not specified, network is considered. (optional)
     * @param network Deprecated. Use chain instead. Optional network identifier which is used to request wallets for a specific network when asset is a multi-chain crypto asset. When both &#39;chain&#39; and &#39;network&#39; are specified, &#39;chain&#39; will take precedence and &#39;network&#39; will be ignored. If &#39;chain&#39; and &#39;network&#39; are not specified, the default &#39;network&#39; (ethereum) will be used. (optional)
     * @return CryptoWallet
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A single wallet object if an asset is specified or an array of wallet objects if no asset is specified </td><td>  -  </td></tr>
     </table>
     */
    public CryptoWallet listCryptoFundingWallets(@javax.annotation.Nullable String asset, @javax.annotation.Nullable CryptoChain chain, @javax.annotation.Nullable String network) throws ApiException {
        ApiResponse<CryptoWallet> localVarResp = listCryptoFundingWalletsWithHttpInfo(asset, chain, network);
        return localVarResp.getData();
    }

    /**
     * Retrieve Crypto Funding Wallets
     * Lists wallets for the account given in the path parameter. If an asset is specified and no wallet for the account and asset pair exists one will be created. If no asset is specified only existing wallets will be listed for the account. An account may have at most one wallet per asset.
     * @param asset Filter by crypto asset symbol, e.g. BTC, ETH, USDT. If specified and no wallet exists, one will be created. (optional)
     * @param chain Optional chain identifier. Use to request wallets for a specific chain when asset is a multi-chain crypto asset. If not specified, network is considered. (optional)
     * @param network Deprecated. Use chain instead. Optional network identifier which is used to request wallets for a specific network when asset is a multi-chain crypto asset. When both &#39;chain&#39; and &#39;network&#39; are specified, &#39;chain&#39; will take precedence and &#39;network&#39; will be ignored. If &#39;chain&#39; and &#39;network&#39; are not specified, the default &#39;network&#39; (ethereum) will be used. (optional)
     * @return ApiResponse&lt;CryptoWallet&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A single wallet object if an asset is specified or an array of wallet objects if no asset is specified </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CryptoWallet> listCryptoFundingWalletsWithHttpInfo(@javax.annotation.Nullable String asset, @javax.annotation.Nullable CryptoChain chain, @javax.annotation.Nullable String network) throws ApiException {
        okhttp3.Call localVarCall = listCryptoFundingWalletsValidateBeforeCall(asset, chain, network, null);
        Type localVarReturnType = new TypeToken<CryptoWallet>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve Crypto Funding Wallets (asynchronously)
     * Lists wallets for the account given in the path parameter. If an asset is specified and no wallet for the account and asset pair exists one will be created. If no asset is specified only existing wallets will be listed for the account. An account may have at most one wallet per asset.
     * @param asset Filter by crypto asset symbol, e.g. BTC, ETH, USDT. If specified and no wallet exists, one will be created. (optional)
     * @param chain Optional chain identifier. Use to request wallets for a specific chain when asset is a multi-chain crypto asset. If not specified, network is considered. (optional)
     * @param network Deprecated. Use chain instead. Optional network identifier which is used to request wallets for a specific network when asset is a multi-chain crypto asset. When both &#39;chain&#39; and &#39;network&#39; are specified, &#39;chain&#39; will take precedence and &#39;network&#39; will be ignored. If &#39;chain&#39; and &#39;network&#39; are not specified, the default &#39;network&#39; (ethereum) will be used. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A single wallet object if an asset is specified or an array of wallet objects if no asset is specified </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listCryptoFundingWalletsAsync(@javax.annotation.Nullable String asset, @javax.annotation.Nullable CryptoChain chain, @javax.annotation.Nullable String network, final ApiCallback<CryptoWallet> _callback) throws ApiException {

        okhttp3.Call localVarCall = listCryptoFundingWalletsValidateBeforeCall(asset, chain, network, _callback);
        Type localVarReturnType = new TypeToken<CryptoWallet>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listWhitelistedAddress
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> An array of whitelisted objects </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listWhitelistedAddressCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/wallets/whitelists";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "API_Key", "API_Secret" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listWhitelistedAddressValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return listWhitelistedAddressCall(_callback);

    }

    /**
     * An array of whitelisted addresses
     * Returns the list of whitelisted withdrawal addresses for your account.
     * @return WhitelistedAddress
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> An array of whitelisted objects </td><td>  -  </td></tr>
     </table>
     */
    public WhitelistedAddress listWhitelistedAddress() throws ApiException {
        ApiResponse<WhitelistedAddress> localVarResp = listWhitelistedAddressWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * An array of whitelisted addresses
     * Returns the list of whitelisted withdrawal addresses for your account.
     * @return ApiResponse&lt;WhitelistedAddress&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> An array of whitelisted objects </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<WhitelistedAddress> listWhitelistedAddressWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = listWhitelistedAddressValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<WhitelistedAddress>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * An array of whitelisted addresses (asynchronously)
     * Returns the list of whitelisted withdrawal addresses for your account.
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> An array of whitelisted objects </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listWhitelistedAddressAsync(final ApiCallback<WhitelistedAddress> _callback) throws ApiException {

        okhttp3.Call localVarCall = listWhitelistedAddressValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<WhitelistedAddress>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
