/*
 * Trading API
 * Alpaca's Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package markets.alpaca.client.openapi.trading.api;

import markets.alpaca.client.openapi.trading.http.ApiCallback;
import markets.alpaca.client.openapi.trading.http.ApiClient;
import markets.alpaca.client.openapi.trading.http.ApiException;
import markets.alpaca.client.openapi.trading.http.ApiResponse;
import markets.alpaca.client.openapi.trading.http.Configuration;
import markets.alpaca.client.openapi.trading.http.Pair;
import markets.alpaca.client.openapi.trading.http.ProgressRequestBody;
import markets.alpaca.client.openapi.trading.http.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import markets.alpaca.client.openapi.trading.model.CreateLocateRequest;
import markets.alpaca.client.openapi.trading.model.ErrorResponse;
import markets.alpaca.client.openapi.trading.model.ListLocateQuotesResponse;
import markets.alpaca.client.openapi.trading.model.ListLocatesResponse;
import java.time.LocalDate;
import markets.alpaca.client.openapi.trading.model.Locate;
import markets.alpaca.client.openapi.trading.model.LocateError;
import markets.alpaca.client.openapi.trading.model.LocateStatus;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated client for LocatesApi operations.
 *
 * <p>This class is generated from the configured OpenAPI spec. Operation method Javadocs include
 * OAS summaries, descriptions, parameters, return types, response details, and external
 * documentation links when present in the spec.
 *
 * <h2>Operations</h2>
 *
 * <ul>
 * 
 *   <li><b>{@code createLocates}</b>: Create Locate</li>
 * 
 *   <li><b>{@code getLocate}</b>: Get Locate</li>
 * 
 *   <li><b>{@code listLocateQuotes}</b>: Get Locate Quotes</li>
 * 
 *   <li><b>{@code listLocates}</b>: List Locates</li>
 * 
 * </ul>
 */
public class LocatesApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public LocatesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public LocatesApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createLocates
     * @param createLocateRequest Locate request details. (required)
     * @param idempotencyKey Optional idempotency key for safe retries. Reusing the same key with the same request returns the original locate response. Reusing the same key with a different request returns HTTP 422. We recommend always providing this header in production so timeouts, network errors, and 5xx responses can be safely retried without creating duplicate locates. Use a client-generated unique value, such as a UUID, for each logical locate.  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid locate request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication headers are missing or invalid. Make sure you authenticate your request with a valid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> User has no access to a resource. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Cannot complete locate request. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error. We recommend retrying these later. If the issue persists, please contact us on Slack or on the Community Forum. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createLocatesCall(@javax.annotation.Nonnull CreateLocateRequest createLocateRequest, @javax.annotation.Nullable String idempotencyKey, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createLocateRequest;

        // create path and map variables
        String localVarPath = "/v1/locates";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (idempotencyKey != null) {
            localVarHeaderParams.put("Idempotency-Key", localVarApiClient.parameterToString(idempotencyKey));
        }


        String[] localVarAuthNames = new String[] { "API_Key", "API_Secret" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createLocatesValidateBeforeCall(@javax.annotation.Nonnull CreateLocateRequest createLocateRequest, @javax.annotation.Nullable String idempotencyKey, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'createLocateRequest' is set
        if (createLocateRequest == null) {
            throw new ApiException("Missing the required parameter 'createLocateRequest' when calling createLocates(Async)");
        }

        return createLocatesCall(createLocateRequest, idempotencyKey, _callback);

    }

    /**
     * Create Locate
     * Creates a locate request for a short sale.
     * @param createLocateRequest Locate request details. (required)
     * @param idempotencyKey Optional idempotency key for safe retries. Reusing the same key with the same request returns the original locate response. Reusing the same key with a different request returns HTTP 422. We recommend always providing this header in production so timeouts, network errors, and 5xx responses can be safely retried without creating duplicate locates. Use a client-generated unique value, such as a UUID, for each logical locate.  (optional)
     * @return Locate
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid locate request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication headers are missing or invalid. Make sure you authenticate your request with a valid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> User has no access to a resource. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Cannot complete locate request. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error. We recommend retrying these later. If the issue persists, please contact us on Slack or on the Community Forum. </td><td>  -  </td></tr>
     </table>
     */
    public Locate createLocates(@javax.annotation.Nonnull CreateLocateRequest createLocateRequest, @javax.annotation.Nullable String idempotencyKey) throws ApiException {
        ApiResponse<Locate> localVarResp = createLocatesWithHttpInfo(createLocateRequest, idempotencyKey);
        return localVarResp.getData();
    }

    /**
     * Create Locate
     * Creates a locate request for a short sale.
     * @param createLocateRequest Locate request details. (required)
     * @param idempotencyKey Optional idempotency key for safe retries. Reusing the same key with the same request returns the original locate response. Reusing the same key with a different request returns HTTP 422. We recommend always providing this header in production so timeouts, network errors, and 5xx responses can be safely retried without creating duplicate locates. Use a client-generated unique value, such as a UUID, for each logical locate.  (optional)
     * @return ApiResponse&lt;Locate&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid locate request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication headers are missing or invalid. Make sure you authenticate your request with a valid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> User has no access to a resource. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Cannot complete locate request. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error. We recommend retrying these later. If the issue persists, please contact us on Slack or on the Community Forum. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Locate> createLocatesWithHttpInfo(@javax.annotation.Nonnull CreateLocateRequest createLocateRequest, @javax.annotation.Nullable String idempotencyKey) throws ApiException {
        okhttp3.Call localVarCall = createLocatesValidateBeforeCall(createLocateRequest, idempotencyKey, null);
        Type localVarReturnType = new TypeToken<Locate>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create Locate (asynchronously)
     * Creates a locate request for a short sale.
     * @param createLocateRequest Locate request details. (required)
     * @param idempotencyKey Optional idempotency key for safe retries. Reusing the same key with the same request returns the original locate response. Reusing the same key with a different request returns HTTP 422. We recommend always providing this header in production so timeouts, network errors, and 5xx responses can be safely retried without creating duplicate locates. Use a client-generated unique value, such as a UUID, for each logical locate.  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid locate request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication headers are missing or invalid. Make sure you authenticate your request with a valid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> User has no access to a resource. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Cannot complete locate request. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error. We recommend retrying these later. If the issue persists, please contact us on Slack or on the Community Forum. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createLocatesAsync(@javax.annotation.Nonnull CreateLocateRequest createLocateRequest, @javax.annotation.Nullable String idempotencyKey, final ApiCallback<Locate> _callback) throws ApiException {

        okhttp3.Call localVarCall = createLocatesValidateBeforeCall(createLocateRequest, idempotencyKey, _callback);
        Type localVarReturnType = new TypeToken<Locate>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getLocate
     * @param locateId The locate ID. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returns the requested locate. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid locate request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication headers are missing or invalid. Make sure you authenticate your request with a valid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> User has no access to a resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error. We recommend retrying these later. If the issue persists, please contact us on Slack or on the Community Forum. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getLocateCall(@javax.annotation.Nonnull UUID locateId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/locates/{locate_id}"
            .replace("{" + "locate_id" + "}", localVarApiClient.escapeString(locateId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "API_Key", "API_Secret" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getLocateValidateBeforeCall(@javax.annotation.Nonnull UUID locateId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'locateId' is set
        if (locateId == null) {
            throw new ApiException("Missing the required parameter 'locateId' when calling getLocate(Async)");
        }

        return getLocateCall(locateId, _callback);

    }

    /**
     * Get Locate
     * Returns a locate by ID.
     * @param locateId The locate ID. (required)
     * @return Locate
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returns the requested locate. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid locate request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication headers are missing or invalid. Make sure you authenticate your request with a valid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> User has no access to a resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error. We recommend retrying these later. If the issue persists, please contact us on Slack or on the Community Forum. </td><td>  -  </td></tr>
     </table>
     */
    public Locate getLocate(@javax.annotation.Nonnull UUID locateId) throws ApiException {
        ApiResponse<Locate> localVarResp = getLocateWithHttpInfo(locateId);
        return localVarResp.getData();
    }

    /**
     * Get Locate
     * Returns a locate by ID.
     * @param locateId The locate ID. (required)
     * @return ApiResponse&lt;Locate&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returns the requested locate. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid locate request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication headers are missing or invalid. Make sure you authenticate your request with a valid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> User has no access to a resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error. We recommend retrying these later. If the issue persists, please contact us on Slack or on the Community Forum. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Locate> getLocateWithHttpInfo(@javax.annotation.Nonnull UUID locateId) throws ApiException {
        okhttp3.Call localVarCall = getLocateValidateBeforeCall(locateId, null);
        Type localVarReturnType = new TypeToken<Locate>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Locate (asynchronously)
     * Returns a locate by ID.
     * @param locateId The locate ID. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returns the requested locate. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid locate request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication headers are missing or invalid. Make sure you authenticate your request with a valid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> User has no access to a resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error. We recommend retrying these later. If the issue persists, please contact us on Slack or on the Community Forum. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getLocateAsync(@javax.annotation.Nonnull UUID locateId, final ApiCallback<Locate> _callback) throws ApiException {

        okhttp3.Call localVarCall = getLocateValidateBeforeCall(locateId, _callback);
        Type localVarReturnType = new TypeToken<Locate>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listLocateQuotes
     * @param symbols Comma-separated list of stock symbols. Maximum 100 unique symbols. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returns locate quotes for the requested symbols. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid locate quote request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication headers are missing or invalid. Make sure you authenticate your request with a valid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> User has no access to a resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error. We recommend retrying these later. If the issue persists, please contact us on Slack or on the Community Forum. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listLocateQuotesCall(@javax.annotation.Nonnull String symbols, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/locates/quotes";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (symbols != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("symbols", symbols));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "API_Key", "API_Secret" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listLocateQuotesValidateBeforeCall(@javax.annotation.Nonnull String symbols, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'symbols' is set
        if (symbols == null) {
            throw new ApiException("Missing the required parameter 'symbols' when calling listLocateQuotes(Async)");
        }

        return listLocateQuotesCall(symbols, _callback);

    }

    /**
     * Get Locate Quotes
     * Returns locate availability and pricing for one or more symbols.
     * @param symbols Comma-separated list of stock symbols. Maximum 100 unique symbols. (required)
     * @return ListLocateQuotesResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returns locate quotes for the requested symbols. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid locate quote request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication headers are missing or invalid. Make sure you authenticate your request with a valid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> User has no access to a resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error. We recommend retrying these later. If the issue persists, please contact us on Slack or on the Community Forum. </td><td>  -  </td></tr>
     </table>
     */
    public ListLocateQuotesResponse listLocateQuotes(@javax.annotation.Nonnull String symbols) throws ApiException {
        ApiResponse<ListLocateQuotesResponse> localVarResp = listLocateQuotesWithHttpInfo(symbols);
        return localVarResp.getData();
    }

    /**
     * Get Locate Quotes
     * Returns locate availability and pricing for one or more symbols.
     * @param symbols Comma-separated list of stock symbols. Maximum 100 unique symbols. (required)
     * @return ApiResponse&lt;ListLocateQuotesResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returns locate quotes for the requested symbols. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid locate quote request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication headers are missing or invalid. Make sure you authenticate your request with a valid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> User has no access to a resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error. We recommend retrying these later. If the issue persists, please contact us on Slack or on the Community Forum. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ListLocateQuotesResponse> listLocateQuotesWithHttpInfo(@javax.annotation.Nonnull String symbols) throws ApiException {
        okhttp3.Call localVarCall = listLocateQuotesValidateBeforeCall(symbols, null);
        Type localVarReturnType = new TypeToken<ListLocateQuotesResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Locate Quotes (asynchronously)
     * Returns locate availability and pricing for one or more symbols.
     * @param symbols Comma-separated list of stock symbols. Maximum 100 unique symbols. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returns locate quotes for the requested symbols. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid locate quote request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication headers are missing or invalid. Make sure you authenticate your request with a valid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> User has no access to a resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error. We recommend retrying these later. If the issue persists, please contact us on Slack or on the Community Forum. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listLocateQuotesAsync(@javax.annotation.Nonnull String symbols, final ApiCallback<ListLocateQuotesResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = listLocateQuotesValidateBeforeCall(symbols, _callback);
        Type localVarReturnType = new TypeToken<ListLocateQuotesResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listLocates
     * @param pageToken Used for pagination, this token retrieves the next page of results. It is obtained from the response of the preceding page when additional pages are available. (optional)
     * @param limit Maximum number of results to return. (optional, default to 1000)
     * @param status Filter by locate status. (optional)
     * @param symbol Filter by stock symbol. (optional)
     * @param start Filter locates with locate trading date on or after this date. Format: YYYY-MM-DD. The locate trading date uses America/New_York and rolls at 8pm ET. (optional)
     * @param end Filter locates with locate trading date before this date (exclusive). Format: YYYY-MM-DD. The locate trading date uses America/New_York and rolls at 8pm ET. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returns a list of locates for the account, or an empty list if no locates are found. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid locate request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication headers are missing or invalid. Make sure you authenticate your request with a valid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> User has no access to a resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error. We recommend retrying these later. If the issue persists, please contact us on Slack or on the Community Forum. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listLocatesCall(@javax.annotation.Nullable String pageToken, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable LocateStatus status, @javax.annotation.Nullable String symbol, @javax.annotation.Nullable LocalDate start, @javax.annotation.Nullable LocalDate end, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/locates";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (pageToken != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page_token", pageToken));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (status != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("status", status));
        }

        if (symbol != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("symbol", symbol));
        }

        if (start != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("start", start));
        }

        if (end != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("end", end));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "API_Key", "API_Secret" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listLocatesValidateBeforeCall(@javax.annotation.Nullable String pageToken, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable LocateStatus status, @javax.annotation.Nullable String symbol, @javax.annotation.Nullable LocalDate start, @javax.annotation.Nullable LocalDate end, final ApiCallback _callback) throws ApiException {
        return listLocatesCall(pageToken, limit, status, symbol, start, end, _callback);

    }

    /**
     * List Locates
     * Returns locates filtered by status, symbol, or date range. Results are sorted by &#x60;created_at&#x60; descending, with &#x60;id&#x60; descending as the tie-breaker.
     * @param pageToken Used for pagination, this token retrieves the next page of results. It is obtained from the response of the preceding page when additional pages are available. (optional)
     * @param limit Maximum number of results to return. (optional, default to 1000)
     * @param status Filter by locate status. (optional)
     * @param symbol Filter by stock symbol. (optional)
     * @param start Filter locates with locate trading date on or after this date. Format: YYYY-MM-DD. The locate trading date uses America/New_York and rolls at 8pm ET. (optional)
     * @param end Filter locates with locate trading date before this date (exclusive). Format: YYYY-MM-DD. The locate trading date uses America/New_York and rolls at 8pm ET. (optional)
     * @return ListLocatesResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returns a list of locates for the account, or an empty list if no locates are found. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid locate request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication headers are missing or invalid. Make sure you authenticate your request with a valid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> User has no access to a resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error. We recommend retrying these later. If the issue persists, please contact us on Slack or on the Community Forum. </td><td>  -  </td></tr>
     </table>
     */
    public ListLocatesResponse listLocates(@javax.annotation.Nullable String pageToken, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable LocateStatus status, @javax.annotation.Nullable String symbol, @javax.annotation.Nullable LocalDate start, @javax.annotation.Nullable LocalDate end) throws ApiException {
        ApiResponse<ListLocatesResponse> localVarResp = listLocatesWithHttpInfo(pageToken, limit, status, symbol, start, end);
        return localVarResp.getData();
    }

    /**
     * List Locates
     * Returns locates filtered by status, symbol, or date range. Results are sorted by &#x60;created_at&#x60; descending, with &#x60;id&#x60; descending as the tie-breaker.
     * @param pageToken Used for pagination, this token retrieves the next page of results. It is obtained from the response of the preceding page when additional pages are available. (optional)
     * @param limit Maximum number of results to return. (optional, default to 1000)
     * @param status Filter by locate status. (optional)
     * @param symbol Filter by stock symbol. (optional)
     * @param start Filter locates with locate trading date on or after this date. Format: YYYY-MM-DD. The locate trading date uses America/New_York and rolls at 8pm ET. (optional)
     * @param end Filter locates with locate trading date before this date (exclusive). Format: YYYY-MM-DD. The locate trading date uses America/New_York and rolls at 8pm ET. (optional)
     * @return ApiResponse&lt;ListLocatesResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returns a list of locates for the account, or an empty list if no locates are found. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid locate request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication headers are missing or invalid. Make sure you authenticate your request with a valid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> User has no access to a resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error. We recommend retrying these later. If the issue persists, please contact us on Slack or on the Community Forum. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ListLocatesResponse> listLocatesWithHttpInfo(@javax.annotation.Nullable String pageToken, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable LocateStatus status, @javax.annotation.Nullable String symbol, @javax.annotation.Nullable LocalDate start, @javax.annotation.Nullable LocalDate end) throws ApiException {
        okhttp3.Call localVarCall = listLocatesValidateBeforeCall(pageToken, limit, status, symbol, start, end, null);
        Type localVarReturnType = new TypeToken<ListLocatesResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List Locates (asynchronously)
     * Returns locates filtered by status, symbol, or date range. Results are sorted by &#x60;created_at&#x60; descending, with &#x60;id&#x60; descending as the tie-breaker.
     * @param pageToken Used for pagination, this token retrieves the next page of results. It is obtained from the response of the preceding page when additional pages are available. (optional)
     * @param limit Maximum number of results to return. (optional, default to 1000)
     * @param status Filter by locate status. (optional)
     * @param symbol Filter by stock symbol. (optional)
     * @param start Filter locates with locate trading date on or after this date. Format: YYYY-MM-DD. The locate trading date uses America/New_York and rolls at 8pm ET. (optional)
     * @param end Filter locates with locate trading date before this date (exclusive). Format: YYYY-MM-DD. The locate trading date uses America/New_York and rolls at 8pm ET. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Returns a list of locates for the account, or an empty list if no locates are found. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid locate request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication headers are missing or invalid. Make sure you authenticate your request with a valid API key. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> User has no access to a resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error. We recommend retrying these later. If the issue persists, please contact us on Slack or on the Community Forum. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listLocatesAsync(@javax.annotation.Nullable String pageToken, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable LocateStatus status, @javax.annotation.Nullable String symbol, @javax.annotation.Nullable LocalDate start, @javax.annotation.Nullable LocalDate end, final ApiCallback<ListLocatesResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = listLocatesValidateBeforeCall(pageToken, limit, status, symbol, start, end, _callback);
        Type localVarReturnType = new TypeToken<ListLocatesResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
