/*
 * Broker API
 * Open brokerage accounts, enable stock, options and crypto trading. Manage the ongoing user experience and brokerage customer lifecycle with the Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package markets.alpaca.client.openapi.broker.http;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonElement;
import io.gsonfire.GsonFireBuilder;
import io.gsonfire.TypeSelector;

import okio.ByteString;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.nio.charset.StandardCharsets;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Date;
import java.util.Locale;
import java.util.Map;
import java.util.HashMap;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter = new OffsetDateTimeTypeAdapter();
    private static LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();
    private static LocalDateTimeTypeAdapter localDateTimeTypeAdapter = new LocalDateTimeTypeAdapter();
    private static ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder()
                .registerTypeSelector(markets.alpaca.client.openapi.broker.model.BatchJournalResponse.class, new TypeSelector<markets.alpaca.client.openapi.broker.model.BatchJournalResponse>() {
                    @Override
                    public Class<? extends markets.alpaca.client.openapi.broker.model.BatchJournalResponse> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("BatchJournalResponse", markets.alpaca.client.openapi.broker.model.BatchJournalResponse.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "entry_type"));
                    }
          })
                .registerTypeSelector(markets.alpaca.client.openapi.broker.model.Journal.class, new TypeSelector<markets.alpaca.client.openapi.broker.model.Journal>() {
                    @Override
                    public Class<? extends markets.alpaca.client.openapi.broker.model.Journal> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("JNLC", markets.alpaca.client.openapi.broker.model.JNLC.class);
                        classByDiscriminatorValue.put("JNLS", markets.alpaca.client.openapi.broker.model.JNLS.class);
                        classByDiscriminatorValue.put("BatchJournalResponse", markets.alpaca.client.openapi.broker.model.BatchJournalResponse.class);
                        classByDiscriminatorValue.put("Journal", markets.alpaca.client.openapi.broker.model.Journal.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "entry_type"));
                    }
          })
        ;
        GsonBuilder builder = fireBuilder.createGsonBuilder();
        return builder;
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if (null == element) {
            throw new IllegalArgumentException("missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    /**
     * Returns the Java class that implements the OpenAPI schema for the specified discriminator value.
     *
     * @param classByDiscriminatorValue The map of discriminator values to Java classes.
     * @param discriminatorValue The value of the OpenAPI discriminator in the input data.
     * @return The Java class that implements the OpenAPI schema
     */
    private static Class getClassByDiscriminator(Map classByDiscriminatorValue, String discriminatorValue) {
        Class clazz = (Class) classByDiscriminatorValue.get(discriminatorValue);
        if (null == clazz) {
            throw new IllegalArgumentException("cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    static {
        GsonBuilder gsonBuilder = createGson();
        gsonBuilder.registerTypeAdapter(Date.class, dateTypeAdapter);
        gsonBuilder.registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter);
        gsonBuilder.registerTypeAdapter(LocalDate.class, localDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(LocalDateTime.class, localDateTimeTypeAdapter);
        gsonBuilder.registerTypeAdapter(byte[].class, byteArrayAdapter);
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.ACHRelationship.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.APRTier.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.APRTierDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AcatcActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AcatsActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.Account.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AccountCashInterestEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AccountCashInterestPatch.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AccountCashInterestPost.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AccountCashInterestProgram.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AccountCashInterestResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AccountConfigurations.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AccountCreationRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AccountDocument.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AccountExtended.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AccountExtendedUsd.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AccountFPSLEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AccountFPSLEventUS.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AccountFPSLItem.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AccountFPSLItemPost.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AccountFPSLPatch.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AccountFPSLPost.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AccountFPSLResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AccountLimit.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AccountStatusEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AccountTradingLimit.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AccountUpdateRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.Activity.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.ActivityEventV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.ActivityEventV2AllOfDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.ActivityEventV2CommonFields.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.ActivityV2DetailNTA.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.ActivityV2DetailTRD.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AdminActionBelongsTo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AdminActionContextLiquidationContext.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AdminActionContextTransactionCancelContext.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AdminActionCreatedBy.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AdminActionEventGeneral.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AdminActionLegacyNote.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AdminActionLiquidation.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AdminActionTransactionCancel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AdminConfigurations.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AdminConfigurationsEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AdminConfigurationsEventAcctDailyTransferLimit.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AdminConfigurationsEventMaxMarginMultiplier.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AdminConfigurationsEventMaxOptionsTradingLevel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AdvancedInstructions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AggregatePositionResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.Agreement.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.Announcement.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.Asset.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AssetEntryRequirements.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.AuthorizeOAuthTokenResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.Bank.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.BankAdditionalFields.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.BatchCreateFundingWalletRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.BatchCreateFundingWalletResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.BatchJournalRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.BatchJournalRequestEntriesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.BatchJournalResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.Beneficiary.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CDIVActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CIPDocument.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CIPIdentity.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CIPInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CIPKYC.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CIPPhoto.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CIPWatchlist.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CSWActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CalendarDay.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.Clock.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.ClockResp.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CommonAcatActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CommonCDIVActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CommonCaActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CommonFixedIncomeInterestActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CommonJournalActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CommonMAActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CommonNCActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CommonNTAActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CommonOPCAActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CommonOptionsActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CommonSDIVActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CommonSpinoffActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CommonSplitActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CommonSplitStockActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CommonVOFSubtypeActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.Contact.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CorrespondentLimit.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CountryInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CreateACHRelationshipRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CreateBankRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CreateCryptoTransferRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CreateFundingWalletRecipientBankRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CreateFundingWalletWithdrawalRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CreateIFTransferRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CreateJITSettlementRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CreateJournalRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CreateOrderRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CreateOrderRequestStopLoss.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CreateOrderRequestTakeProfit.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CreateSettlementRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CreateTransferRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CreateWatchlistRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CreateWhitelistedAddressRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CryptoTransfer.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CryptoWallet.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.CustodialAccountMinorIdentity.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.DIVNRAActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.DIVSPDActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.DIVWHActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.DailyCashInterest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.DailyTradingLimit.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.DemoFundingTransfer.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.DisclosureContextAnnotation.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.Disclosures.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.EoDCashInterestReportResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.Error.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.ExchangeOfferActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.ExerciseRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.ExerciseResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.FEEActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.FOPTActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.FPSLAnalyticsLoansResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.FPSLError.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.FPSLInterest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.FPSLLoan.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.FPSLTier.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.FixedIncomeInterestActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.FixedIncomeRedemptionActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.ForwardSplitActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.FundingDetail.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.FundingWallet.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.FundingWalletRecipientBank.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.FundingWalletTransfer.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.GetCryptoTransferEstimate200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.GetOptionsContracts200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.GetV1AccountsAccountIdOnfidoSdkTokens200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.GetV1AccountsPositions200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.GetV1RebalancingRuns200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.GetV1RebalancingSubscriptions200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.GetV1ReportingEodPositions200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.GetV1TradingAccountsAccountIdOrdersEstimationRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.GetV1TransfersJitLedgerIdBalances200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.GetV1TransfersJitReports200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.IFFee.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.IPOEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.IPOOffering.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.IPOOfferingListResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.IPOOfferingResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.Identity.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.InstantFunding.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.Interest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.IssueOAuthTokenResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.JITLedgerAccount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.JITReport.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.JITReportDownloadURL.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.JNLC.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.JNLCActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.JNLS.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.JNLSActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.JournalStatusEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.JournalStatusEventV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.KYCResults.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.LegacyCalendarDay.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.LegacyClock.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.ListAPRTiersResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.ListFPSLLoansResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.ListFundingDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.ListTransfersResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.MAActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.MEMActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.MLegOrderLeg.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.NCActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.NonTradeActivity.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.NonTradeActivityEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OAuthTokenRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OCTActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OPASNActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OPEXCActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OPEXPActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OPTRDActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OathClientResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OpcaCDIVActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OpcaFSPLITActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OpcaMAActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OpcaNCActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OpcaRSPLITActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OpcaSDIVActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OpcaSPINActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OpcaUSPLITActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OptionContract.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OptionDeliverable.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OptionsApprovalEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OptionsApprovalRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OptionsApprovalResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OptionsApprovalsList.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.Order.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OrderClosedResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OrderLeg.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OvercontributedIRAAccount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OwnerDocument.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.OwnerDocumentUploadRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.PatchV1AccountsAccountIdOnfidoSdkRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.PatchV1RebalancingPortfoliosPortfolioIdRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.Portfolio.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.PortfolioHistory.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.PortfolioRun.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.PortfolioSubscription.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.PortfolioWeights.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.Position.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.PositionClosedResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.PostV1RebalancingPortfoliosRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.PostV1RebalancingRunsRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.PostV1RebalancingSubscriptionsRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.PostV1TradingAccountsAccountIdWatchlistsWatchlistIdRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.PublicCalendarResp.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.PublicMarket.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.RebalancingConditions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.ReportsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.RestrictToLiquidationReasons.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.ReverseBatchJournalRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.ReverseBatchJournalRequestEntriesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.ReverseSplitActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.RightsDistributionActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.RightsSubscriptionElectionActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.SDIVActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.SettlementAccount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.SettlementResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.SettlementTransfer.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.SettlementsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.SkippedOrder.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.SpinoffActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.StatusFundingEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.SubscribeToAdminActionSSE200ResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.SystemEventV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.TenderOfferActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.TokenizationMintCallback.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.TokenizationMintRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.TokenizationMintResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.TokenizationRedeemRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.TokenizationRedeemResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.TokenizationRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.TradeAccount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.TradeActivity.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.TradeUpdateEventV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.TradeUpdateEventV2Leg.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.Transaction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.Transfer.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.TransferFee.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.TransferIRA.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.TransferIRADetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.TransferIRATaxWithholding.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.TransferStatusEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.TransmitterInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.TrustedContact.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.USDAccountTradingLimit.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.USDPosition.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.UnitSplitActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.UpdateOrderRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.UsCorporate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.UsCorporatesResp.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.UsTreasuriesResp.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.UsTreasury.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.Usd.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.W8benDocument.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.WRMActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.WarrantExerciseElectionActivityV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.Watchlist.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.WatchlistWithoutAsset.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new markets.alpaca.client.openapi.broker.model.WhitelistedAddress.CustomTypeAdapterFactory());
        gson = gsonBuilder.create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /**
    * Deserialize the given JSON InputStream to a Java object.
    *
    * @param <T>         Type
    * @param inputStream The JSON InputStream
    * @param returnType  The type to deserialize into
    * @return The deserialized Java object
    */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(InputStream inputStream, Type returnType) throws IOException {
        try (InputStreamReader reader = new InputStreamReader(inputStream, StandardCharsets.UTF_8)) {
        if (isLenientOnJson) {
            // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
            JsonReader jsonReader = new JsonReader(reader);
            jsonReader.setLenient(true);
            return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(reader, returnType);
            }
        }
    }

    /**
     * Gson TypeAdapter for Byte Array type
     */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String bytesAsBase64 = in.nextString();
                    ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                    return byteString.toByteArray();
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 OffsetDateTime type
     */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    if (date.endsWith("+0000")) {
                        date = date.substring(0, date.length()-5) + "Z";
                    }
                    return OffsetDateTime.parse(date, formatter);
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDate type
     */
    public static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDate.parse(date, formatter);
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDateTime type
     */
    public static class LocalDateTimeTypeAdapter extends TypeAdapter<LocalDateTime> {

        private DateTimeFormatter formatter;

        public LocalDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE_TIME);
        }

        public LocalDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        return LocalDateTime.parse(date, formatter);
                    } catch (DateTimeParseException e) {
                        if (date.length() > 10 && date.charAt(10) == ' ') {
                            date = date.substring(0, 10) + 'T' + date.substring(11);
                            return LocalDateTime.parse(date, formatter);
                        }
                        throw e;
                    }
            }
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateTimeFormat(DateTimeFormatter dateFormat) {
        localDateTimeTypeAdapter.setFormat(dateFormat);
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {}

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {}

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                return dateFormat.parse(date);
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
