/*
 * Trading API
 * Alpaca's Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package markets.alpaca.client.openapi.trading.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets phase
 */
@JsonAdapter(Phase.Adapter.class)
public enum Phase implements Serializable {
  
  CLOSED("closed"),
  
  PRE("pre"),
  
  CORE("core"),
  
  LUNCH("lunch"),
  
  POST("post");

  private String value;

  Phase(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Phase fromValue(String value) {
    for (Phase b : Phase.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<Phase> {
    @Override
    public void write(final JsonWriter jsonWriter, final Phase enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Phase read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Phase.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    Phase.fromValue(value);
  }
}

