/*
 * Broker API
 * Open brokerage accounts, enable stock, options and crypto trading. Manage the ongoing user experience and brokerage customer lifecycle with the Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package markets.alpaca.client.openapi.broker.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import markets.alpaca.client.openapi.broker.model.AcatsAccountType;
import markets.alpaca.client.openapi.broker.model.AcatsContraBrokerType;
import markets.alpaca.client.openapi.broker.model.AcatsDtccTransferType;
import markets.alpaca.client.openapi.broker.model.AcatsRejectionDetails;
import markets.alpaca.client.openapi.broker.model.AcatsStatusDetails;
import markets.alpaca.client.openapi.broker.model.AcatsTransferDirection;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import markets.alpaca.client.openapi.broker.http.JSON;

/**
 * An ACATS transfer and its current status.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class AcatsTransfer implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ACATS_ID = "acats_id";
  @SerializedName(SERIALIZED_NAME_ACATS_ID)
  @javax.annotation.Nonnull
  private UUID acatsId;

  public static final String SERIALIZED_NAME_ACCOUNT_ID = "account_id";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ID)
  @javax.annotation.Nonnull
  private UUID accountId;

  public static final String SERIALIZED_NAME_ACCOUNT_NAME = "account_name";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_NAME)
  @javax.annotation.Nullable
  private String accountName;

  public static final String SERIALIZED_NAME_ACCOUNT_NUMBER = "account_number";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_NUMBER)
  @javax.annotation.Nonnull
  private String accountNumber;

  public static final String SERIALIZED_NAME_ACCOUNT_TYPE = "account_type";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_TYPE)
  @javax.annotation.Nullable
  private AcatsAccountType accountType;

  public static final String SERIALIZED_NAME_CONTRA_ACCOUNT_NUMBER = "contra_account_number";
  @SerializedName(SERIALIZED_NAME_CONTRA_ACCOUNT_NUMBER)
  @javax.annotation.Nonnull
  private String contraAccountNumber;

  public static final String SERIALIZED_NAME_CONTRA_BROKER_NAME = "contra_broker_name";
  @SerializedName(SERIALIZED_NAME_CONTRA_BROKER_NAME)
  @javax.annotation.Nullable
  private String contraBrokerName;

  public static final String SERIALIZED_NAME_CONTRA_BROKER_NUMBER = "contra_broker_number";
  @SerializedName(SERIALIZED_NAME_CONTRA_BROKER_NUMBER)
  @javax.annotation.Nonnull
  private String contraBrokerNumber;

  public static final String SERIALIZED_NAME_CONTRA_BROKER_TYPE = "contra_broker_type";
  @SerializedName(SERIALIZED_NAME_CONTRA_BROKER_TYPE)
  @javax.annotation.Nullable
  private AcatsContraBrokerType contraBrokerType;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_DIRECTION = "direction";
  @SerializedName(SERIALIZED_NAME_DIRECTION)
  @javax.annotation.Nonnull
  private AcatsTransferDirection direction;

  public static final String SERIALIZED_NAME_IP_ADDRESS = "ip_address";
  @SerializedName(SERIALIZED_NAME_IP_ADDRESS)
  @javax.annotation.Nullable
  private String ipAddress;

  public static final String SERIALIZED_NAME_ORIGINAL_TRANSFER_IDENTIFIER = "original_transfer_identifier";
  @SerializedName(SERIALIZED_NAME_ORIGINAL_TRANSFER_IDENTIFIER)
  @javax.annotation.Nullable
  private String originalTransferIdentifier;

  public static final String SERIALIZED_NAME_REJECTION_DETAILS = "rejection_details";
  @SerializedName(SERIALIZED_NAME_REJECTION_DETAILS)
  @javax.annotation.Nullable
  private AcatsRejectionDetails rejectionDetails;

  public static final String SERIALIZED_NAME_SETTLEMENT_DATE = "settlement_date";
  @SerializedName(SERIALIZED_NAME_SETTLEMENT_DATE)
  @javax.annotation.Nullable
  private OffsetDateTime settlementDate;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private AcatsStatusDetails status;

  public static final String SERIALIZED_NAME_TOTAL_TRANSFER_VALUE = "total_transfer_value";
  @SerializedName(SERIALIZED_NAME_TOTAL_TRANSFER_VALUE)
  @javax.annotation.Nullable
  private BigDecimal totalTransferValue;

  public static final String SERIALIZED_NAME_TRANSFER_IDENTIFIER = "transfer_identifier";
  @SerializedName(SERIALIZED_NAME_TRANSFER_IDENTIFIER)
  @javax.annotation.Nullable
  private String transferIdentifier;

  public static final String SERIALIZED_NAME_TRANSFER_TYPE = "transfer_type";
  @SerializedName(SERIALIZED_NAME_TRANSFER_TYPE)
  @javax.annotation.Nonnull
  private AcatsDtccTransferType transferType;

  public AcatsTransfer() {
  }

  public AcatsTransfer acatsId(@javax.annotation.Nonnull UUID acatsId) {
    this.acatsId = acatsId;
    return this;
  }

  /**
   * The ID of the ACATS transfer
   * @return acatsId
   */
  @javax.annotation.Nonnull
  public UUID getAcatsId() {
    return acatsId;
  }

  public void setAcatsId(@javax.annotation.Nonnull UUID acatsId) {
    this.acatsId = acatsId;
  }


  public AcatsTransfer accountId(@javax.annotation.Nonnull UUID accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * Account ID associated with the ACATS transfer
   * @return accountId
   */
  @javax.annotation.Nonnull
  public UUID getAccountId() {
    return accountId;
  }

  public void setAccountId(@javax.annotation.Nonnull UUID accountId) {
    this.accountId = accountId;
  }


  public AcatsTransfer accountName(@javax.annotation.Nullable String accountName) {
    this.accountName = accountName;
    return this;
  }

  /**
   * Name on the Alpaca account associated with the transfer
   * @return accountName
   */
  @javax.annotation.Nullable
  public String getAccountName() {
    return accountName;
  }

  public void setAccountName(@javax.annotation.Nullable String accountName) {
    this.accountName = accountName;
  }


  public AcatsTransfer accountNumber(@javax.annotation.Nonnull String accountNumber) {
    this.accountNumber = accountNumber;
    return this;
  }

  /**
   * Account number at Alpaca
   * @return accountNumber
   */
  @javax.annotation.Nonnull
  public String getAccountNumber() {
    return accountNumber;
  }

  public void setAccountNumber(@javax.annotation.Nonnull String accountNumber) {
    this.accountNumber = accountNumber;
  }


  public AcatsTransfer accountType(@javax.annotation.Nullable AcatsAccountType accountType) {
    this.accountType = accountType;
    return this;
  }

  /**
   * Get accountType
   * @return accountType
   */
  @javax.annotation.Nullable
  public AcatsAccountType getAccountType() {
    return accountType;
  }

  public void setAccountType(@javax.annotation.Nullable AcatsAccountType accountType) {
    this.accountType = accountType;
  }


  public AcatsTransfer contraAccountNumber(@javax.annotation.Nonnull String contraAccountNumber) {
    this.contraAccountNumber = contraAccountNumber;
    return this;
  }

  /**
   * Account number at the contra broker
   * @return contraAccountNumber
   */
  @javax.annotation.Nonnull
  public String getContraAccountNumber() {
    return contraAccountNumber;
  }

  public void setContraAccountNumber(@javax.annotation.Nonnull String contraAccountNumber) {
    this.contraAccountNumber = contraAccountNumber;
  }


  public AcatsTransfer contraBrokerName(@javax.annotation.Nullable String contraBrokerName) {
    this.contraBrokerName = contraBrokerName;
    return this;
  }

  /**
   * Name of the contra broker
   * @return contraBrokerName
   */
  @javax.annotation.Nullable
  public String getContraBrokerName() {
    return contraBrokerName;
  }

  public void setContraBrokerName(@javax.annotation.Nullable String contraBrokerName) {
    this.contraBrokerName = contraBrokerName;
  }


  public AcatsTransfer contraBrokerNumber(@javax.annotation.Nonnull String contraBrokerNumber) {
    this.contraBrokerNumber = contraBrokerNumber;
    return this;
  }

  /**
   * DTCC account number for the contra broker
   * @return contraBrokerNumber
   */
  @javax.annotation.Nonnull
  public String getContraBrokerNumber() {
    return contraBrokerNumber;
  }

  public void setContraBrokerNumber(@javax.annotation.Nonnull String contraBrokerNumber) {
    this.contraBrokerNumber = contraBrokerNumber;
  }


  public AcatsTransfer contraBrokerType(@javax.annotation.Nullable AcatsContraBrokerType contraBrokerType) {
    this.contraBrokerType = contraBrokerType;
    return this;
  }

  /**
   * Get contraBrokerType
   * @return contraBrokerType
   */
  @javax.annotation.Nullable
  public AcatsContraBrokerType getContraBrokerType() {
    return contraBrokerType;
  }

  public void setContraBrokerType(@javax.annotation.Nullable AcatsContraBrokerType contraBrokerType) {
    this.contraBrokerType = contraBrokerType;
  }


  public AcatsTransfer createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Timestamp in RFC-3339 format with microsecond precision
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public AcatsTransfer direction(@javax.annotation.Nonnull AcatsTransferDirection direction) {
    this.direction = direction;
    return this;
  }

  /**
   * Get direction
   * @return direction
   */
  @javax.annotation.Nonnull
  public AcatsTransferDirection getDirection() {
    return direction;
  }

  public void setDirection(@javax.annotation.Nonnull AcatsTransferDirection direction) {
    this.direction = direction;
  }


  public AcatsTransfer ipAddress(@javax.annotation.Nullable String ipAddress) {
    this.ipAddress = ipAddress;
    return this;
  }

  /**
   * User&#39;s IP address (IPv4 or IPv6) at time of submission
   * @return ipAddress
   */
  @javax.annotation.Nullable
  public String getIpAddress() {
    return ipAddress;
  }

  public void setIpAddress(@javax.annotation.Nullable String ipAddress) {
    this.ipAddress = ipAddress;
  }


  public AcatsTransfer originalTransferIdentifier(@javax.annotation.Nullable String originalTransferIdentifier) {
    this.originalTransferIdentifier = originalTransferIdentifier;
    return this;
  }

  /**
   * DTCC transfer identifier for a previous, related transfer
   * @return originalTransferIdentifier
   */
  @javax.annotation.Nullable
  public String getOriginalTransferIdentifier() {
    return originalTransferIdentifier;
  }

  public void setOriginalTransferIdentifier(@javax.annotation.Nullable String originalTransferIdentifier) {
    this.originalTransferIdentifier = originalTransferIdentifier;
  }


  public AcatsTransfer rejectionDetails(@javax.annotation.Nullable AcatsRejectionDetails rejectionDetails) {
    this.rejectionDetails = rejectionDetails;
    return this;
  }

  /**
   * Get rejectionDetails
   * @return rejectionDetails
   */
  @javax.annotation.Nullable
  public AcatsRejectionDetails getRejectionDetails() {
    return rejectionDetails;
  }

  public void setRejectionDetails(@javax.annotation.Nullable AcatsRejectionDetails rejectionDetails) {
    this.rejectionDetails = rejectionDetails;
  }


  public AcatsTransfer settlementDate(@javax.annotation.Nullable OffsetDateTime settlementDate) {
    this.settlementDate = settlementDate;
    return this;
  }

  /**
   * Timestamp in RFC-3339 format with microsecond precision
   * @return settlementDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getSettlementDate() {
    return settlementDate;
  }

  public void setSettlementDate(@javax.annotation.Nullable OffsetDateTime settlementDate) {
    this.settlementDate = settlementDate;
  }


  public AcatsTransfer status(@javax.annotation.Nonnull AcatsStatusDetails status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public AcatsStatusDetails getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull AcatsStatusDetails status) {
    this.status = status;
  }


  public AcatsTransfer totalTransferValue(@javax.annotation.Nullable BigDecimal totalTransferValue) {
    this.totalTransferValue = totalTransferValue;
    return this;
  }

  /**
   * Total transfer value is the sum of the market value of all assets and securities in an ACAT at the time of settlement, plus any cash balance.
   * @return totalTransferValue
   */
  @javax.annotation.Nullable
  public BigDecimal getTotalTransferValue() {
    return totalTransferValue;
  }

  public void setTotalTransferValue(@javax.annotation.Nullable BigDecimal totalTransferValue) {
    this.totalTransferValue = totalTransferValue;
  }


  public AcatsTransfer transferIdentifier(@javax.annotation.Nullable String transferIdentifier) {
    this.transferIdentifier = transferIdentifier;
    return this;
  }

  /**
   * DTCC transfer identifier, also known as the control number
   * @return transferIdentifier
   */
  @javax.annotation.Nullable
  public String getTransferIdentifier() {
    return transferIdentifier;
  }

  public void setTransferIdentifier(@javax.annotation.Nullable String transferIdentifier) {
    this.transferIdentifier = transferIdentifier;
  }


  public AcatsTransfer transferType(@javax.annotation.Nonnull AcatsDtccTransferType transferType) {
    this.transferType = transferType;
    return this;
  }

  /**
   * Get transferType
   * @return transferType
   */
  @javax.annotation.Nonnull
  public AcatsDtccTransferType getTransferType() {
    return transferType;
  }

  public void setTransferType(@javax.annotation.Nonnull AcatsDtccTransferType transferType) {
    this.transferType = transferType;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AcatsTransfer instance itself
   */
  public AcatsTransfer putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AcatsTransfer acatsTransfer = (AcatsTransfer) o;
    return Objects.equals(this.acatsId, acatsTransfer.acatsId) &&
        Objects.equals(this.accountId, acatsTransfer.accountId) &&
        Objects.equals(this.accountName, acatsTransfer.accountName) &&
        Objects.equals(this.accountNumber, acatsTransfer.accountNumber) &&
        Objects.equals(this.accountType, acatsTransfer.accountType) &&
        Objects.equals(this.contraAccountNumber, acatsTransfer.contraAccountNumber) &&
        Objects.equals(this.contraBrokerName, acatsTransfer.contraBrokerName) &&
        Objects.equals(this.contraBrokerNumber, acatsTransfer.contraBrokerNumber) &&
        Objects.equals(this.contraBrokerType, acatsTransfer.contraBrokerType) &&
        Objects.equals(this.createdAt, acatsTransfer.createdAt) &&
        Objects.equals(this.direction, acatsTransfer.direction) &&
        Objects.equals(this.ipAddress, acatsTransfer.ipAddress) &&
        Objects.equals(this.originalTransferIdentifier, acatsTransfer.originalTransferIdentifier) &&
        Objects.equals(this.rejectionDetails, acatsTransfer.rejectionDetails) &&
        Objects.equals(this.settlementDate, acatsTransfer.settlementDate) &&
        Objects.equals(this.status, acatsTransfer.status) &&
        Objects.equals(this.totalTransferValue, acatsTransfer.totalTransferValue) &&
        Objects.equals(this.transferIdentifier, acatsTransfer.transferIdentifier) &&
        Objects.equals(this.transferType, acatsTransfer.transferType)&&
        Objects.equals(this.additionalProperties, acatsTransfer.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acatsId, accountId, accountName, accountNumber, accountType, contraAccountNumber, contraBrokerName, contraBrokerNumber, contraBrokerType, createdAt, direction, ipAddress, originalTransferIdentifier, rejectionDetails, settlementDate, status, totalTransferValue, transferIdentifier, transferType, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AcatsTransfer {\n");
    sb.append("    acatsId: ").append(toIndentedString(acatsId)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    contraAccountNumber: ").append(toIndentedString(contraAccountNumber)).append("\n");
    sb.append("    contraBrokerName: ").append(toIndentedString(contraBrokerName)).append("\n");
    sb.append("    contraBrokerNumber: ").append(toIndentedString(contraBrokerNumber)).append("\n");
    sb.append("    contraBrokerType: ").append(toIndentedString(contraBrokerType)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("    originalTransferIdentifier: ").append(toIndentedString(originalTransferIdentifier)).append("\n");
    sb.append("    rejectionDetails: ").append(toIndentedString(rejectionDetails)).append("\n");
    sb.append("    settlementDate: ").append(toIndentedString(settlementDate)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    totalTransferValue: ").append(toIndentedString(totalTransferValue)).append("\n");
    sb.append("    transferIdentifier: ").append(toIndentedString(transferIdentifier)).append("\n");
    sb.append("    transferType: ").append(toIndentedString(transferType)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("acats_id", "account_id", "account_name", "account_number", "account_type", "contra_account_number", "contra_broker_name", "contra_broker_number", "contra_broker_type", "created_at", "direction", "ip_address", "original_transfer_identifier", "rejection_details", "settlement_date", "status", "total_transfer_value", "transfer_identifier", "transfer_type"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("acats_id", "account_id", "account_number", "contra_account_number", "contra_broker_number", "created_at", "direction", "status", "transfer_type"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AcatsTransfer
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AcatsTransfer.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AcatsTransfer is not found in the empty JSON string", AcatsTransfer.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AcatsTransfer.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("acats_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `acats_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("acats_id").toString()));
      }
      if (!jsonObj.get("account_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `account_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("account_id").toString()));
      }
      if ((jsonObj.get("account_name") != null && !jsonObj.get("account_name").isJsonNull()) && !jsonObj.get("account_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `account_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("account_name").toString()));
      }
      if (!jsonObj.get("account_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `account_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("account_number").toString()));
      }
      // validate the optional field `account_type`
      if (jsonObj.get("account_type") != null && !jsonObj.get("account_type").isJsonNull()) {
        AcatsAccountType.validateJsonElement(jsonObj.get("account_type"));
      }
      if (!jsonObj.get("contra_account_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `contra_account_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contra_account_number").toString()));
      }
      if ((jsonObj.get("contra_broker_name") != null && !jsonObj.get("contra_broker_name").isJsonNull()) && !jsonObj.get("contra_broker_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `contra_broker_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contra_broker_name").toString()));
      }
      if (!jsonObj.get("contra_broker_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `contra_broker_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contra_broker_number").toString()));
      }
      // validate the optional field `contra_broker_type`
      if (jsonObj.get("contra_broker_type") != null && !jsonObj.get("contra_broker_type").isJsonNull()) {
        AcatsContraBrokerType.validateJsonElement(jsonObj.get("contra_broker_type"));
      }
      // validate the required field `direction`
      AcatsTransferDirection.validateJsonElement(jsonObj.get("direction"));
      if ((jsonObj.get("ip_address") != null && !jsonObj.get("ip_address").isJsonNull()) && !jsonObj.get("ip_address").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ip_address` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ip_address").toString()));
      }
      if ((jsonObj.get("original_transfer_identifier") != null && !jsonObj.get("original_transfer_identifier").isJsonNull()) && !jsonObj.get("original_transfer_identifier").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `original_transfer_identifier` to be a primitive type in the JSON string but got `%s`", jsonObj.get("original_transfer_identifier").toString()));
      }
      // validate the optional field `rejection_details`
      if (jsonObj.get("rejection_details") != null && !jsonObj.get("rejection_details").isJsonNull()) {
        AcatsRejectionDetails.validateJsonElement(jsonObj.get("rejection_details"));
      }
      // validate the required field `status`
      AcatsStatusDetails.validateJsonElement(jsonObj.get("status"));
      if ((jsonObj.get("total_transfer_value") != null && !jsonObj.get("total_transfer_value").isJsonNull()) && !jsonObj.get("total_transfer_value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `total_transfer_value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("total_transfer_value").toString()));
      }
      if ((jsonObj.get("transfer_identifier") != null && !jsonObj.get("transfer_identifier").isJsonNull()) && !jsonObj.get("transfer_identifier").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `transfer_identifier` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transfer_identifier").toString()));
      }
      // validate the required field `transfer_type`
      AcatsDtccTransferType.validateJsonElement(jsonObj.get("transfer_type"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AcatsTransfer.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AcatsTransfer' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AcatsTransfer> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AcatsTransfer.class));

       return (TypeAdapter<T>) new TypeAdapter<AcatsTransfer>() {
           @Override
           public void write(JsonWriter out, AcatsTransfer value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AcatsTransfer read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             AcatsTransfer instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AcatsTransfer given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AcatsTransfer
   * @throws IOException if the JSON string is invalid with respect to AcatsTransfer
   */
  public static AcatsTransfer fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AcatsTransfer.class);
  }

  /**
   * Convert an instance of AcatsTransfer to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

