/*
 * Broker API
 * Open brokerage accounts, enable stock, options and crypto trading. Manage the ongoing user experience and brokerage customer lifecycle with the Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package markets.alpaca.client.openapi.broker.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import java.util.UUID;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import markets.alpaca.client.openapi.broker.http.JSON;

/**
 * Activity details for a fill or partial_fill event
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class ActivityV2DetailTRD implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ASSET_ID = "asset_id";
  @SerializedName(SERIALIZED_NAME_ASSET_ID)
  @javax.annotation.Nullable
  private UUID assetId;

  public static final String SERIALIZED_NAME_CLIENT_ORDER_ID = "client_order_id";
  @SerializedName(SERIALIZED_NAME_CLIENT_ORDER_ID)
  @javax.annotation.Nullable
  private String clientOrderId;

  public static final String SERIALIZED_NAME_COMMISSION = "commission";
  @SerializedName(SERIALIZED_NAME_COMMISSION)
  @javax.annotation.Nullable
  private BigDecimal commission;

  public static final String SERIALIZED_NAME_CUM_QTY = "cum_qty";
  @SerializedName(SERIALIZED_NAME_CUM_QTY)
  @javax.annotation.Nullable
  private BigDecimal cumQty;

  public static final String SERIALIZED_NAME_CUSIP = "cusip";
  @SerializedName(SERIALIZED_NAME_CUSIP)
  @javax.annotation.Nullable
  private String cusip;

  /**
   * The execution type
   */
  @JsonAdapter(ExecutionTypeEnum.Adapter.class)
  public enum ExecutionTypeEnum {
    FILL("fill"),
    
    TRADE_CORRECT("trade_correct"),
    
    TRADE_BUST("trade_bust");

    private String value;

    ExecutionTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ExecutionTypeEnum fromValue(String value) {
      for (ExecutionTypeEnum b : ExecutionTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ExecutionTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ExecutionTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ExecutionTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ExecutionTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ExecutionTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_EXECUTION_TYPE = "execution_type";
  @SerializedName(SERIALIZED_NAME_EXECUTION_TYPE)
  @javax.annotation.Nullable
  private ExecutionTypeEnum executionType;

  public static final String SERIALIZED_NAME_LEAVES_QTY = "leaves_qty";
  @SerializedName(SERIALIZED_NAME_LEAVES_QTY)
  @javax.annotation.Nullable
  private BigDecimal leavesQty;

  public static final String SERIALIZED_NAME_ORDER_ID = "order_id";
  @SerializedName(SERIALIZED_NAME_ORDER_ID)
  @javax.annotation.Nullable
  private UUID orderId;

  public static final String SERIALIZED_NAME_ORDER_STATUS = "order_status";
  @SerializedName(SERIALIZED_NAME_ORDER_STATUS)
  @javax.annotation.Nullable
  private String orderStatus;

  /**
   * Represents what side of the transaction an order was on
   */
  @JsonAdapter(SideEnum.Adapter.class)
  public enum SideEnum {
    BUY("buy"),
    
    SELL("sell");

    private String value;

    SideEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SideEnum fromValue(String value) {
      for (SideEnum b : SideEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SideEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SideEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SideEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SideEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      SideEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_SIDE = "side";
  @SerializedName(SERIALIZED_NAME_SIDE)
  @javax.annotation.Nullable
  private SideEnum side;

  public static final String SERIALIZED_NAME_SYMBOL = "symbol";
  @SerializedName(SERIALIZED_NAME_SYMBOL)
  @javax.annotation.Nullable
  private String symbol;

  public ActivityV2DetailTRD() {
  }

  public ActivityV2DetailTRD assetId(@javax.annotation.Nullable UUID assetId) {
    this.assetId = assetId;
    return this;
  }

  /**
   * Asset ID (For options this represents the option contract ID)
   * @return assetId
   */
  @javax.annotation.Nullable
  public UUID getAssetId() {
    return assetId;
  }

  public void setAssetId(@javax.annotation.Nullable UUID assetId) {
    this.assetId = assetId;
  }


  public ActivityV2DetailTRD clientOrderId(@javax.annotation.Nullable String clientOrderId) {
    this.clientOrderId = clientOrderId;
    return this;
  }

  /**
   * Order ID provided by the customer
   * @return clientOrderId
   */
  @javax.annotation.Nullable
  public String getClientOrderId() {
    return clientOrderId;
  }

  public void setClientOrderId(@javax.annotation.Nullable String clientOrderId) {
    this.clientOrderId = clientOrderId;
  }


  public ActivityV2DetailTRD commission(@javax.annotation.Nullable BigDecimal commission) {
    this.commission = commission;
    return this;
  }

  /**
   * Commission to collect from the account holder
   * @return commission
   */
  @javax.annotation.Nullable
  public BigDecimal getCommission() {
    return commission;
  }

  public void setCommission(@javax.annotation.Nullable BigDecimal commission) {
    this.commission = commission;
  }


  public ActivityV2DetailTRD cumQty(@javax.annotation.Nullable BigDecimal cumQty) {
    this.cumQty = cumQty;
    return this;
  }

  /**
   * Total filled quantity on the order
   * @return cumQty
   */
  @javax.annotation.Nullable
  public BigDecimal getCumQty() {
    return cumQty;
  }

  public void setCumQty(@javax.annotation.Nullable BigDecimal cumQty) {
    this.cumQty = cumQty;
  }


  public ActivityV2DetailTRD cusip(@javax.annotation.Nullable String cusip) {
    this.cusip = cusip;
    return this;
  }

  /**
   * CUSIP of the security involved with the activity
   * @return cusip
   */
  @javax.annotation.Nullable
  public String getCusip() {
    return cusip;
  }

  public void setCusip(@javax.annotation.Nullable String cusip) {
    this.cusip = cusip;
  }


  public ActivityV2DetailTRD executionType(@javax.annotation.Nullable ExecutionTypeEnum executionType) {
    this.executionType = executionType;
    return this;
  }

  /**
   * The execution type
   * @return executionType
   */
  @javax.annotation.Nullable
  public ExecutionTypeEnum getExecutionType() {
    return executionType;
  }

  public void setExecutionType(@javax.annotation.Nullable ExecutionTypeEnum executionType) {
    this.executionType = executionType;
  }


  public ActivityV2DetailTRD leavesQty(@javax.annotation.Nullable BigDecimal leavesQty) {
    this.leavesQty = leavesQty;
    return this;
  }

  /**
   * Unfilled quantity on the order, when order is filled value could be 0
   * @return leavesQty
   */
  @javax.annotation.Nullable
  public BigDecimal getLeavesQty() {
    return leavesQty;
  }

  public void setLeavesQty(@javax.annotation.Nullable BigDecimal leavesQty) {
    this.leavesQty = leavesQty;
  }


  public ActivityV2DetailTRD orderId(@javax.annotation.Nullable UUID orderId) {
    this.orderId = orderId;
    return this;
  }

  /**
   * Order ID generated by Alpaca
   * @return orderId
   */
  @javax.annotation.Nullable
  public UUID getOrderId() {
    return orderId;
  }

  public void setOrderId(@javax.annotation.Nullable UUID orderId) {
    this.orderId = orderId;
  }


  public ActivityV2DetailTRD orderStatus(@javax.annotation.Nullable String orderStatus) {
    this.orderStatus = orderStatus;
    return this;
  }

  /**
   * Identifies the current status of the order
   * @return orderStatus
   */
  @javax.annotation.Nullable
  public String getOrderStatus() {
    return orderStatus;
  }

  public void setOrderStatus(@javax.annotation.Nullable String orderStatus) {
    this.orderStatus = orderStatus;
  }


  public ActivityV2DetailTRD side(@javax.annotation.Nullable SideEnum side) {
    this.side = side;
    return this;
  }

  /**
   * Represents what side of the transaction an order was on
   * @return side
   */
  @javax.annotation.Nullable
  public SideEnum getSide() {
    return side;
  }

  public void setSide(@javax.annotation.Nullable SideEnum side) {
    this.side = side;
  }


  public ActivityV2DetailTRD symbol(@javax.annotation.Nullable String symbol) {
    this.symbol = symbol;
    return this;
  }

  /**
   * The symbol of the security involved with the activity
   * @return symbol
   */
  @javax.annotation.Nullable
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(@javax.annotation.Nullable String symbol) {
    this.symbol = symbol;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ActivityV2DetailTRD instance itself
   */
  public ActivityV2DetailTRD putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivityV2DetailTRD activityV2DetailTRD = (ActivityV2DetailTRD) o;
    return Objects.equals(this.assetId, activityV2DetailTRD.assetId) &&
        Objects.equals(this.clientOrderId, activityV2DetailTRD.clientOrderId) &&
        Objects.equals(this.commission, activityV2DetailTRD.commission) &&
        Objects.equals(this.cumQty, activityV2DetailTRD.cumQty) &&
        Objects.equals(this.cusip, activityV2DetailTRD.cusip) &&
        Objects.equals(this.executionType, activityV2DetailTRD.executionType) &&
        Objects.equals(this.leavesQty, activityV2DetailTRD.leavesQty) &&
        Objects.equals(this.orderId, activityV2DetailTRD.orderId) &&
        Objects.equals(this.orderStatus, activityV2DetailTRD.orderStatus) &&
        Objects.equals(this.side, activityV2DetailTRD.side) &&
        Objects.equals(this.symbol, activityV2DetailTRD.symbol)&&
        Objects.equals(this.additionalProperties, activityV2DetailTRD.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assetId, clientOrderId, commission, cumQty, cusip, executionType, leavesQty, orderId, orderStatus, side, symbol, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActivityV2DetailTRD {\n");
    sb.append("    assetId: ").append(toIndentedString(assetId)).append("\n");
    sb.append("    clientOrderId: ").append(toIndentedString(clientOrderId)).append("\n");
    sb.append("    commission: ").append(toIndentedString(commission)).append("\n");
    sb.append("    cumQty: ").append(toIndentedString(cumQty)).append("\n");
    sb.append("    cusip: ").append(toIndentedString(cusip)).append("\n");
    sb.append("    executionType: ").append(toIndentedString(executionType)).append("\n");
    sb.append("    leavesQty: ").append(toIndentedString(leavesQty)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    orderStatus: ").append(toIndentedString(orderStatus)).append("\n");
    sb.append("    side: ").append(toIndentedString(side)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("asset_id", "client_order_id", "commission", "cum_qty", "cusip", "execution_type", "leaves_qty", "order_id", "order_status", "side", "symbol"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ActivityV2DetailTRD
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ActivityV2DetailTRD.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ActivityV2DetailTRD is not found in the empty JSON string", ActivityV2DetailTRD.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("asset_id") != null && !jsonObj.get("asset_id").isJsonNull()) && !jsonObj.get("asset_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `asset_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("asset_id").toString()));
      }
      if ((jsonObj.get("client_order_id") != null && !jsonObj.get("client_order_id").isJsonNull()) && !jsonObj.get("client_order_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `client_order_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("client_order_id").toString()));
      }
      if ((jsonObj.get("commission") != null && !jsonObj.get("commission").isJsonNull()) && !jsonObj.get("commission").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `commission` to be a primitive type in the JSON string but got `%s`", jsonObj.get("commission").toString()));
      }
      if ((jsonObj.get("cum_qty") != null && !jsonObj.get("cum_qty").isJsonNull()) && !jsonObj.get("cum_qty").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `cum_qty` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cum_qty").toString()));
      }
      if ((jsonObj.get("cusip") != null && !jsonObj.get("cusip").isJsonNull()) && !jsonObj.get("cusip").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `cusip` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cusip").toString()));
      }
      if ((jsonObj.get("execution_type") != null && !jsonObj.get("execution_type").isJsonNull()) && !jsonObj.get("execution_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `execution_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("execution_type").toString()));
      }
      // validate the optional field `execution_type`
      if (jsonObj.get("execution_type") != null && !jsonObj.get("execution_type").isJsonNull()) {
        ExecutionTypeEnum.validateJsonElement(jsonObj.get("execution_type"));
      }
      if ((jsonObj.get("leaves_qty") != null && !jsonObj.get("leaves_qty").isJsonNull()) && !jsonObj.get("leaves_qty").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `leaves_qty` to be a primitive type in the JSON string but got `%s`", jsonObj.get("leaves_qty").toString()));
      }
      if ((jsonObj.get("order_id") != null && !jsonObj.get("order_id").isJsonNull()) && !jsonObj.get("order_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `order_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("order_id").toString()));
      }
      if ((jsonObj.get("order_status") != null && !jsonObj.get("order_status").isJsonNull()) && !jsonObj.get("order_status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `order_status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("order_status").toString()));
      }
      if ((jsonObj.get("side") != null && !jsonObj.get("side").isJsonNull()) && !jsonObj.get("side").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `side` to be a primitive type in the JSON string but got `%s`", jsonObj.get("side").toString()));
      }
      // validate the optional field `side`
      if (jsonObj.get("side") != null && !jsonObj.get("side").isJsonNull()) {
        SideEnum.validateJsonElement(jsonObj.get("side"));
      }
      if ((jsonObj.get("symbol") != null && !jsonObj.get("symbol").isJsonNull()) && !jsonObj.get("symbol").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `symbol` to be a primitive type in the JSON string but got `%s`", jsonObj.get("symbol").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ActivityV2DetailTRD.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ActivityV2DetailTRD' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ActivityV2DetailTRD> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ActivityV2DetailTRD.class));

       return (TypeAdapter<T>) new TypeAdapter<ActivityV2DetailTRD>() {
           @Override
           public void write(JsonWriter out, ActivityV2DetailTRD value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonNull()) {
                     obj.add(entry.getKey(), JsonNull.INSTANCE);
                   } else if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ActivityV2DetailTRD read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             ActivityV2DetailTRD instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ActivityV2DetailTRD given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ActivityV2DetailTRD
   * @throws IOException if the JSON string is invalid with respect to ActivityV2DetailTRD
   */
  public static ActivityV2DetailTRD fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ActivityV2DetailTRD.class);
  }

  /**
   * Convert an instance of ActivityV2DetailTRD to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

