/*
 * Broker API
 * Open brokerage accounts, enable stock, options and crypto trading. Manage the ongoing user experience and brokerage customer lifecycle with the Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package markets.alpaca.client.openapi.broker.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import markets.alpaca.client.openapi.broker.model.RestrictToLiquidationReasons;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import markets.alpaca.client.openapi.broker.http.JSON;

/**
 * These configurations show account properties that are overriden either by Alpaca Broker Operations or an automated process.  These values cannot be modified by the Broker Partners.  This schema represents the current, effective value of each configuration (e.g. as returned by the get trading account endpoint). For the shape of the payloads broadcast by the **events** streaming API when these values change, see [AdminConfigurationsEvent](#/components/schemas/AdminConfigurationsEvent).
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class AdminConfigurations implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ACCT_DAILY_TRANSFER_LIMIT = "acct_daily_transfer_limit";
  @SerializedName(SERIALIZED_NAME_ACCT_DAILY_TRANSFER_LIMIT)
  @javax.annotation.Nullable
  private BigDecimal acctDailyTransferLimit;

  public static final String SERIALIZED_NAME_ALLOW_INSTANT_ACH = "allow_instant_ach";
  @SerializedName(SERIALIZED_NAME_ALLOW_INSTANT_ACH)
  @javax.annotation.Nullable
  private Boolean allowInstantAch;

  public static final String SERIALIZED_NAME_DISABLE_ALGODASH_ACCESS = "disable_algodash_access";
  @SerializedName(SERIALIZED_NAME_DISABLE_ALGODASH_ACCESS)
  @javax.annotation.Nullable
  private Boolean disableAlgodashAccess;

  public static final String SERIALIZED_NAME_DISABLE_API_KEY = "disable_api_key";
  @SerializedName(SERIALIZED_NAME_DISABLE_API_KEY)
  @javax.annotation.Nullable
  private Boolean disableApiKey;

  public static final String SERIALIZED_NAME_DISABLE_CRYPTO = "disable_crypto";
  @SerializedName(SERIALIZED_NAME_DISABLE_CRYPTO)
  @javax.annotation.Nullable
  private Boolean disableCrypto;

  public static final String SERIALIZED_NAME_DISABLE_DAY_TRADING = "disable_day_trading";
  @SerializedName(SERIALIZED_NAME_DISABLE_DAY_TRADING)
  @javax.annotation.Nullable
  private Boolean disableDayTrading;

  public static final String SERIALIZED_NAME_DISABLE_FRACTIONAL = "disable_fractional";
  @SerializedName(SERIALIZED_NAME_DISABLE_FRACTIONAL)
  @javax.annotation.Nullable
  private Boolean disableFractional;

  public static final String SERIALIZED_NAME_DISABLE_SHORTING = "disable_shorting";
  @SerializedName(SERIALIZED_NAME_DISABLE_SHORTING)
  @javax.annotation.Nullable
  private Boolean disableShorting;

  public static final String SERIALIZED_NAME_INCOMING_TRANSFERS_BLOCKED = "incoming_transfers_blocked";
  @SerializedName(SERIALIZED_NAME_INCOMING_TRANSFERS_BLOCKED)
  @javax.annotation.Nullable
  private Boolean incomingTransfersBlocked;

  public static final String SERIALIZED_NAME_MAX_MARGIN_MULTIPLIER = "max_margin_multiplier";
  @SerializedName(SERIALIZED_NAME_MAX_MARGIN_MULTIPLIER)
  @javax.annotation.Nullable
  private String maxMarginMultiplier;

  /**
   * The max options trading level set by admin for this account. 0&#x3D;disabled, 1&#x3D;Covered Call/Cash-Secured Put, 2&#x3D;Long Call/Put, 3&#x3D;Spreads/Straddles. 
   */
  @JsonAdapter(MaxOptionsTradingLevelEnum.Adapter.class)
  public enum MaxOptionsTradingLevelEnum {
    NUMBER_0(0),
    
    NUMBER_1(1),
    
    NUMBER_2(2),
    
    NUMBER_3(3);

    private Integer value;

    MaxOptionsTradingLevelEnum(Integer value) {
      this.value = value;
    }

    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static MaxOptionsTradingLevelEnum fromValue(Integer value) {
      for (MaxOptionsTradingLevelEnum b : MaxOptionsTradingLevelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<MaxOptionsTradingLevelEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final MaxOptionsTradingLevelEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public MaxOptionsTradingLevelEnum read(final JsonReader jsonReader) throws IOException {
        Integer value =  jsonReader.nextInt();
        return MaxOptionsTradingLevelEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      Integer value = jsonElement.getAsInt();
      MaxOptionsTradingLevelEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_MAX_OPTIONS_TRADING_LEVEL = "max_options_trading_level";
  @SerializedName(SERIALIZED_NAME_MAX_OPTIONS_TRADING_LEVEL)
  @javax.annotation.Nullable
  private MaxOptionsTradingLevelEnum maxOptionsTradingLevel;

  public static final String SERIALIZED_NAME_OUTGOING_TRANSFERS_BLOCKED = "outgoing_transfers_blocked";
  @SerializedName(SERIALIZED_NAME_OUTGOING_TRANSFERS_BLOCKED)
  @javax.annotation.Nullable
  private Boolean outgoingTransfersBlocked;

  public static final String SERIALIZED_NAME_RESTRICT_TO_LIQUIDATION_REASONS = "restrict_to_liquidation_reasons";
  @SerializedName(SERIALIZED_NAME_RESTRICT_TO_LIQUIDATION_REASONS)
  @javax.annotation.Nullable
  private RestrictToLiquidationReasons restrictToLiquidationReasons;

  public AdminConfigurations() {
  }

  public AdminConfigurations acctDailyTransferLimit(@javax.annotation.Nullable BigDecimal acctDailyTransferLimit) {
    this.acctDailyTransferLimit = acctDailyTransferLimit;
    return this;
  }

  /**
   * Override the correspondent level daily transfer limits
   * @return acctDailyTransferLimit
   */
  @javax.annotation.Nullable
  public BigDecimal getAcctDailyTransferLimit() {
    return acctDailyTransferLimit;
  }

  public void setAcctDailyTransferLimit(@javax.annotation.Nullable BigDecimal acctDailyTransferLimit) {
    this.acctDailyTransferLimit = acctDailyTransferLimit;
  }


  public AdminConfigurations allowInstantAch(@javax.annotation.Nullable Boolean allowInstantAch) {
    this.allowInstantAch = allowInstantAch;
    return this;
  }

  /**
   * If true, the account is allowed to perform instant ACH
   * @return allowInstantAch
   */
  @javax.annotation.Nullable
  public Boolean getAllowInstantAch() {
    return allowInstantAch;
  }

  public void setAllowInstantAch(@javax.annotation.Nullable Boolean allowInstantAch) {
    this.allowInstantAch = allowInstantAch;
  }


  public AdminConfigurations disableAlgodashAccess(@javax.annotation.Nullable Boolean disableAlgodashAccess) {
    this.disableAlgodashAccess = disableAlgodashAccess;
    return this;
  }

  /**
   * If true, the account is allowed to access algo dash
   * @return disableAlgodashAccess
   */
  @javax.annotation.Nullable
  public Boolean getDisableAlgodashAccess() {
    return disableAlgodashAccess;
  }

  public void setDisableAlgodashAccess(@javax.annotation.Nullable Boolean disableAlgodashAccess) {
    this.disableAlgodashAccess = disableAlgodashAccess;
  }


  public AdminConfigurations disableApiKey(@javax.annotation.Nullable Boolean disableApiKey) {
    this.disableApiKey = disableApiKey;
    return this;
  }

  /**
   * If true, the account&#39;s API key will be disabled
   * @return disableApiKey
   */
  @javax.annotation.Nullable
  public Boolean getDisableApiKey() {
    return disableApiKey;
  }

  public void setDisableApiKey(@javax.annotation.Nullable Boolean disableApiKey) {
    this.disableApiKey = disableApiKey;
  }


  public AdminConfigurations disableCrypto(@javax.annotation.Nullable Boolean disableCrypto) {
    this.disableCrypto = disableCrypto;
    return this;
  }

  /**
   * If true, the account is not allowed to trade cryptos
   * @return disableCrypto
   */
  @javax.annotation.Nullable
  public Boolean getDisableCrypto() {
    return disableCrypto;
  }

  public void setDisableCrypto(@javax.annotation.Nullable Boolean disableCrypto) {
    this.disableCrypto = disableCrypto;
  }


  public AdminConfigurations disableDayTrading(@javax.annotation.Nullable Boolean disableDayTrading) {
    this.disableDayTrading = disableDayTrading;
    return this;
  }

  /**
   * If true, the account is not allowed to day trade (e.g. buy and sell the same security on the same day)
   * @return disableDayTrading
   */
  @javax.annotation.Nullable
  public Boolean getDisableDayTrading() {
    return disableDayTrading;
  }

  public void setDisableDayTrading(@javax.annotation.Nullable Boolean disableDayTrading) {
    this.disableDayTrading = disableDayTrading;
  }


  public AdminConfigurations disableFractional(@javax.annotation.Nullable Boolean disableFractional) {
    this.disableFractional = disableFractional;
    return this;
  }

  /**
   * If true, the account cannot create orders for fractional share positions
   * @return disableFractional
   */
  @javax.annotation.Nullable
  public Boolean getDisableFractional() {
    return disableFractional;
  }

  public void setDisableFractional(@javax.annotation.Nullable Boolean disableFractional) {
    this.disableFractional = disableFractional;
  }


  public AdminConfigurations disableShorting(@javax.annotation.Nullable Boolean disableShorting) {
    this.disableShorting = disableShorting;
    return this;
  }

  /**
   * If true the account is not allowed to create short position orders
   * @return disableShorting
   */
  @javax.annotation.Nullable
  public Boolean getDisableShorting() {
    return disableShorting;
  }

  public void setDisableShorting(@javax.annotation.Nullable Boolean disableShorting) {
    this.disableShorting = disableShorting;
  }


  public AdminConfigurations incomingTransfersBlocked(@javax.annotation.Nullable Boolean incomingTransfersBlocked) {
    this.incomingTransfersBlocked = incomingTransfersBlocked;
    return this;
  }

  /**
   * If true, incoming transfers to this account are rejected
   * @return incomingTransfersBlocked
   */
  @javax.annotation.Nullable
  public Boolean getIncomingTransfersBlocked() {
    return incomingTransfersBlocked;
  }

  public void setIncomingTransfersBlocked(@javax.annotation.Nullable Boolean incomingTransfersBlocked) {
    this.incomingTransfersBlocked = incomingTransfersBlocked;
  }


  public AdminConfigurations maxMarginMultiplier(@javax.annotation.Nullable String maxMarginMultiplier) {
    this.maxMarginMultiplier = maxMarginMultiplier;
    return this;
  }

  /**
   * The max margin multiplier set by admin for this account. Can be \&quot;1\&quot;, \&quot;2\&quot;, or \&quot;4\&quot;.
   * @return maxMarginMultiplier
   */
  @javax.annotation.Nullable
  public String getMaxMarginMultiplier() {
    return maxMarginMultiplier;
  }

  public void setMaxMarginMultiplier(@javax.annotation.Nullable String maxMarginMultiplier) {
    this.maxMarginMultiplier = maxMarginMultiplier;
  }


  public AdminConfigurations maxOptionsTradingLevel(@javax.annotation.Nullable MaxOptionsTradingLevelEnum maxOptionsTradingLevel) {
    this.maxOptionsTradingLevel = maxOptionsTradingLevel;
    return this;
  }

  /**
   * The max options trading level set by admin for this account. 0&#x3D;disabled, 1&#x3D;Covered Call/Cash-Secured Put, 2&#x3D;Long Call/Put, 3&#x3D;Spreads/Straddles. 
   * @return maxOptionsTradingLevel
   */
  @javax.annotation.Nullable
  public MaxOptionsTradingLevelEnum getMaxOptionsTradingLevel() {
    return maxOptionsTradingLevel;
  }

  public void setMaxOptionsTradingLevel(@javax.annotation.Nullable MaxOptionsTradingLevelEnum maxOptionsTradingLevel) {
    this.maxOptionsTradingLevel = maxOptionsTradingLevel;
  }


  public AdminConfigurations outgoingTransfersBlocked(@javax.annotation.Nullable Boolean outgoingTransfersBlocked) {
    this.outgoingTransfersBlocked = outgoingTransfersBlocked;
    return this;
  }

  /**
   * If true, outgoing transfers from this account are rejected
   * @return outgoingTransfersBlocked
   */
  @javax.annotation.Nullable
  public Boolean getOutgoingTransfersBlocked() {
    return outgoingTransfersBlocked;
  }

  public void setOutgoingTransfersBlocked(@javax.annotation.Nullable Boolean outgoingTransfersBlocked) {
    this.outgoingTransfersBlocked = outgoingTransfersBlocked;
  }


  public AdminConfigurations restrictToLiquidationReasons(@javax.annotation.Nullable RestrictToLiquidationReasons restrictToLiquidationReasons) {
    this.restrictToLiquidationReasons = restrictToLiquidationReasons;
    return this;
  }

  /**
   * Get restrictToLiquidationReasons
   * @return restrictToLiquidationReasons
   */
  @javax.annotation.Nullable
  public RestrictToLiquidationReasons getRestrictToLiquidationReasons() {
    return restrictToLiquidationReasons;
  }

  public void setRestrictToLiquidationReasons(@javax.annotation.Nullable RestrictToLiquidationReasons restrictToLiquidationReasons) {
    this.restrictToLiquidationReasons = restrictToLiquidationReasons;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AdminConfigurations instance itself
   */
  public AdminConfigurations putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminConfigurations adminConfigurations = (AdminConfigurations) o;
    return Objects.equals(this.acctDailyTransferLimit, adminConfigurations.acctDailyTransferLimit) &&
        Objects.equals(this.allowInstantAch, adminConfigurations.allowInstantAch) &&
        Objects.equals(this.disableAlgodashAccess, adminConfigurations.disableAlgodashAccess) &&
        Objects.equals(this.disableApiKey, adminConfigurations.disableApiKey) &&
        Objects.equals(this.disableCrypto, adminConfigurations.disableCrypto) &&
        Objects.equals(this.disableDayTrading, adminConfigurations.disableDayTrading) &&
        Objects.equals(this.disableFractional, adminConfigurations.disableFractional) &&
        Objects.equals(this.disableShorting, adminConfigurations.disableShorting) &&
        Objects.equals(this.incomingTransfersBlocked, adminConfigurations.incomingTransfersBlocked) &&
        Objects.equals(this.maxMarginMultiplier, adminConfigurations.maxMarginMultiplier) &&
        Objects.equals(this.maxOptionsTradingLevel, adminConfigurations.maxOptionsTradingLevel) &&
        Objects.equals(this.outgoingTransfersBlocked, adminConfigurations.outgoingTransfersBlocked) &&
        Objects.equals(this.restrictToLiquidationReasons, adminConfigurations.restrictToLiquidationReasons)&&
        Objects.equals(this.additionalProperties, adminConfigurations.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acctDailyTransferLimit, allowInstantAch, disableAlgodashAccess, disableApiKey, disableCrypto, disableDayTrading, disableFractional, disableShorting, incomingTransfersBlocked, maxMarginMultiplier, maxOptionsTradingLevel, outgoingTransfersBlocked, restrictToLiquidationReasons, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminConfigurations {\n");
    sb.append("    acctDailyTransferLimit: ").append(toIndentedString(acctDailyTransferLimit)).append("\n");
    sb.append("    allowInstantAch: ").append(toIndentedString(allowInstantAch)).append("\n");
    sb.append("    disableAlgodashAccess: ").append(toIndentedString(disableAlgodashAccess)).append("\n");
    sb.append("    disableApiKey: ").append(toIndentedString(disableApiKey)).append("\n");
    sb.append("    disableCrypto: ").append(toIndentedString(disableCrypto)).append("\n");
    sb.append("    disableDayTrading: ").append(toIndentedString(disableDayTrading)).append("\n");
    sb.append("    disableFractional: ").append(toIndentedString(disableFractional)).append("\n");
    sb.append("    disableShorting: ").append(toIndentedString(disableShorting)).append("\n");
    sb.append("    incomingTransfersBlocked: ").append(toIndentedString(incomingTransfersBlocked)).append("\n");
    sb.append("    maxMarginMultiplier: ").append(toIndentedString(maxMarginMultiplier)).append("\n");
    sb.append("    maxOptionsTradingLevel: ").append(toIndentedString(maxOptionsTradingLevel)).append("\n");
    sb.append("    outgoingTransfersBlocked: ").append(toIndentedString(outgoingTransfersBlocked)).append("\n");
    sb.append("    restrictToLiquidationReasons: ").append(toIndentedString(restrictToLiquidationReasons)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("acct_daily_transfer_limit", "allow_instant_ach", "disable_algodash_access", "disable_api_key", "disable_crypto", "disable_day_trading", "disable_fractional", "disable_shorting", "incoming_transfers_blocked", "max_margin_multiplier", "max_options_trading_level", "outgoing_transfers_blocked", "restrict_to_liquidation_reasons"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AdminConfigurations
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AdminConfigurations.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AdminConfigurations is not found in the empty JSON string", AdminConfigurations.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("acct_daily_transfer_limit") != null && !jsonObj.get("acct_daily_transfer_limit").isJsonNull()) && !jsonObj.get("acct_daily_transfer_limit").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `acct_daily_transfer_limit` to be a primitive type in the JSON string but got `%s`", jsonObj.get("acct_daily_transfer_limit").toString()));
      }
      if ((jsonObj.get("max_margin_multiplier") != null && !jsonObj.get("max_margin_multiplier").isJsonNull()) && !jsonObj.get("max_margin_multiplier").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `max_margin_multiplier` to be a primitive type in the JSON string but got `%s`", jsonObj.get("max_margin_multiplier").toString()));
      }
      // validate the optional field `max_options_trading_level`
      if (jsonObj.get("max_options_trading_level") != null && !jsonObj.get("max_options_trading_level").isJsonNull()) {
        MaxOptionsTradingLevelEnum.validateJsonElement(jsonObj.get("max_options_trading_level"));
      }
      // validate the optional field `restrict_to_liquidation_reasons`
      if (jsonObj.get("restrict_to_liquidation_reasons") != null && !jsonObj.get("restrict_to_liquidation_reasons").isJsonNull()) {
        RestrictToLiquidationReasons.validateJsonElement(jsonObj.get("restrict_to_liquidation_reasons"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AdminConfigurations.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AdminConfigurations' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AdminConfigurations> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AdminConfigurations.class));

       return (TypeAdapter<T>) new TypeAdapter<AdminConfigurations>() {
           @Override
           public void write(JsonWriter out, AdminConfigurations value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonNull()) {
                     obj.add(entry.getKey(), JsonNull.INSTANCE);
                   } else if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AdminConfigurations read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             AdminConfigurations instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AdminConfigurations given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AdminConfigurations
   * @throws IOException if the JSON string is invalid with respect to AdminConfigurations
   */
  public static AdminConfigurations fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AdminConfigurations.class);
  }

  /**
   * Convert an instance of AdminConfigurations to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

