/*
 * Broker API
 * Open brokerage accounts, enable stock, options and crypto trading. Manage the ongoing user experience and brokerage customer lifecycle with the Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package markets.alpaca.client.openapi.broker.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;
import markets.alpaca.client.openapi.broker.model.TaxIdType;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import markets.alpaca.client.openapi.broker.http.JSON;

/**
 * Represents Identity information for a minor that an account of type \&quot;custodial\&quot; is for
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class CustodialAccountMinorIdentity implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_COUNTRY_OF_BIRTH = "country_of_birth";
  @SerializedName(SERIALIZED_NAME_COUNTRY_OF_BIRTH)
  @javax.annotation.Nullable
  private String countryOfBirth;

  public static final String SERIALIZED_NAME_COUNTRY_OF_CITIZENSHIP = "country_of_citizenship";
  @SerializedName(SERIALIZED_NAME_COUNTRY_OF_CITIZENSHIP)
  @javax.annotation.Nullable
  private String countryOfCitizenship;

  public static final String SERIALIZED_NAME_COUNTRY_OF_TAX_RESIDENCE = "country_of_tax_residence";
  @SerializedName(SERIALIZED_NAME_COUNTRY_OF_TAX_RESIDENCE)
  @javax.annotation.Nonnull
  private String countryOfTaxResidence;

  public static final String SERIALIZED_NAME_DATE_OF_BIRTH = "date_of_birth";
  @SerializedName(SERIALIZED_NAME_DATE_OF_BIRTH)
  @javax.annotation.Nonnull
  private LocalDate dateOfBirth;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  @javax.annotation.Nonnull
  private String email;

  public static final String SERIALIZED_NAME_FAMILY_NAME = "family_name";
  @SerializedName(SERIALIZED_NAME_FAMILY_NAME)
  @javax.annotation.Nonnull
  private String familyName;

  public static final String SERIALIZED_NAME_GIVEN_NAME = "given_name";
  @SerializedName(SERIALIZED_NAME_GIVEN_NAME)
  @javax.annotation.Nonnull
  private String givenName;

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  @javax.annotation.Nonnull
  private String state;

  public static final String SERIALIZED_NAME_TAX_ID = "tax_id";
  @SerializedName(SERIALIZED_NAME_TAX_ID)
  @javax.annotation.Nullable
  private String taxId;

  public static final String SERIALIZED_NAME_TAX_ID_TYPE = "tax_id_type";
  @SerializedName(SERIALIZED_NAME_TAX_ID_TYPE)
  @javax.annotation.Nullable
  private TaxIdType taxIdType;

  public CustodialAccountMinorIdentity() {
  }

  public CustodialAccountMinorIdentity countryOfBirth(@javax.annotation.Nullable String countryOfBirth) {
    this.countryOfBirth = countryOfBirth;
    return this;
  }

  /**
   * Get countryOfBirth
   * @return countryOfBirth
   */
  @javax.annotation.Nullable
  public String getCountryOfBirth() {
    return countryOfBirth;
  }

  public void setCountryOfBirth(@javax.annotation.Nullable String countryOfBirth) {
    this.countryOfBirth = countryOfBirth;
  }


  public CustodialAccountMinorIdentity countryOfCitizenship(@javax.annotation.Nullable String countryOfCitizenship) {
    this.countryOfCitizenship = countryOfCitizenship;
    return this;
  }

  /**
   * Get countryOfCitizenship
   * @return countryOfCitizenship
   */
  @javax.annotation.Nullable
  public String getCountryOfCitizenship() {
    return countryOfCitizenship;
  }

  public void setCountryOfCitizenship(@javax.annotation.Nullable String countryOfCitizenship) {
    this.countryOfCitizenship = countryOfCitizenship;
  }


  public CustodialAccountMinorIdentity countryOfTaxResidence(@javax.annotation.Nonnull String countryOfTaxResidence) {
    this.countryOfTaxResidence = countryOfTaxResidence;
    return this;
  }

  /**
   * Get countryOfTaxResidence
   * @return countryOfTaxResidence
   */
  @javax.annotation.Nonnull
  public String getCountryOfTaxResidence() {
    return countryOfTaxResidence;
  }

  public void setCountryOfTaxResidence(@javax.annotation.Nonnull String countryOfTaxResidence) {
    this.countryOfTaxResidence = countryOfTaxResidence;
  }


  public CustodialAccountMinorIdentity dateOfBirth(@javax.annotation.Nonnull LocalDate dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
    return this;
  }

  /**
   * Get dateOfBirth
   * @return dateOfBirth
   */
  @javax.annotation.Nonnull
  public LocalDate getDateOfBirth() {
    return dateOfBirth;
  }

  public void setDateOfBirth(@javax.annotation.Nonnull LocalDate dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
  }


  public CustodialAccountMinorIdentity email(@javax.annotation.Nonnull String email) {
    this.email = email;
    return this;
  }

  /**
   * Get email
   * @return email
   */
  @javax.annotation.Nonnull
  public String getEmail() {
    return email;
  }

  public void setEmail(@javax.annotation.Nonnull String email) {
    this.email = email;
  }


  public CustodialAccountMinorIdentity familyName(@javax.annotation.Nonnull String familyName) {
    this.familyName = familyName;
    return this;
  }

  /**
   * Get familyName
   * @return familyName
   */
  @javax.annotation.Nonnull
  public String getFamilyName() {
    return familyName;
  }

  public void setFamilyName(@javax.annotation.Nonnull String familyName) {
    this.familyName = familyName;
  }


  public CustodialAccountMinorIdentity givenName(@javax.annotation.Nonnull String givenName) {
    this.givenName = givenName;
    return this;
  }

  /**
   * Get givenName
   * @return givenName
   */
  @javax.annotation.Nonnull
  public String getGivenName() {
    return givenName;
  }

  public void setGivenName(@javax.annotation.Nonnull String givenName) {
    this.givenName = givenName;
  }


  public CustodialAccountMinorIdentity state(@javax.annotation.Nonnull String state) {
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   */
  @javax.annotation.Nonnull
  public String getState() {
    return state;
  }

  public void setState(@javax.annotation.Nonnull String state) {
    this.state = state;
  }


  public CustodialAccountMinorIdentity taxId(@javax.annotation.Nullable String taxId) {
    this.taxId = taxId;
    return this;
  }

  /**
   * Get taxId
   * @return taxId
   */
  @javax.annotation.Nullable
  public String getTaxId() {
    return taxId;
  }

  public void setTaxId(@javax.annotation.Nullable String taxId) {
    this.taxId = taxId;
  }


  public CustodialAccountMinorIdentity taxIdType(@javax.annotation.Nullable TaxIdType taxIdType) {
    this.taxIdType = taxIdType;
    return this;
  }

  /**
   * Get taxIdType
   * @return taxIdType
   */
  @javax.annotation.Nullable
  public TaxIdType getTaxIdType() {
    return taxIdType;
  }

  public void setTaxIdType(@javax.annotation.Nullable TaxIdType taxIdType) {
    this.taxIdType = taxIdType;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CustodialAccountMinorIdentity instance itself
   */
  public CustodialAccountMinorIdentity putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustodialAccountMinorIdentity custodialAccountMinorIdentity = (CustodialAccountMinorIdentity) o;
    return Objects.equals(this.countryOfBirth, custodialAccountMinorIdentity.countryOfBirth) &&
        Objects.equals(this.countryOfCitizenship, custodialAccountMinorIdentity.countryOfCitizenship) &&
        Objects.equals(this.countryOfTaxResidence, custodialAccountMinorIdentity.countryOfTaxResidence) &&
        Objects.equals(this.dateOfBirth, custodialAccountMinorIdentity.dateOfBirth) &&
        Objects.equals(this.email, custodialAccountMinorIdentity.email) &&
        Objects.equals(this.familyName, custodialAccountMinorIdentity.familyName) &&
        Objects.equals(this.givenName, custodialAccountMinorIdentity.givenName) &&
        Objects.equals(this.state, custodialAccountMinorIdentity.state) &&
        Objects.equals(this.taxId, custodialAccountMinorIdentity.taxId) &&
        Objects.equals(this.taxIdType, custodialAccountMinorIdentity.taxIdType)&&
        Objects.equals(this.additionalProperties, custodialAccountMinorIdentity.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countryOfBirth, countryOfCitizenship, countryOfTaxResidence, dateOfBirth, email, familyName, givenName, state, taxId, taxIdType, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustodialAccountMinorIdentity {\n");
    sb.append("    countryOfBirth: ").append(toIndentedString(countryOfBirth)).append("\n");
    sb.append("    countryOfCitizenship: ").append(toIndentedString(countryOfCitizenship)).append("\n");
    sb.append("    countryOfTaxResidence: ").append(toIndentedString(countryOfTaxResidence)).append("\n");
    sb.append("    dateOfBirth: ").append(toIndentedString(dateOfBirth)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    familyName: ").append(toIndentedString(familyName)).append("\n");
    sb.append("    givenName: ").append(toIndentedString(givenName)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    taxId: ").append(toIndentedString(taxId)).append("\n");
    sb.append("    taxIdType: ").append(toIndentedString(taxIdType)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("country_of_birth", "country_of_citizenship", "country_of_tax_residence", "date_of_birth", "email", "family_name", "given_name", "state", "tax_id", "tax_id_type"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("country_of_tax_residence", "date_of_birth", "email", "family_name", "given_name", "state"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CustodialAccountMinorIdentity
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CustodialAccountMinorIdentity.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CustodialAccountMinorIdentity is not found in the empty JSON string", CustodialAccountMinorIdentity.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CustodialAccountMinorIdentity.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("country_of_birth") != null && !jsonObj.get("country_of_birth").isJsonNull()) && !jsonObj.get("country_of_birth").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `country_of_birth` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country_of_birth").toString()));
      }
      if ((jsonObj.get("country_of_citizenship") != null && !jsonObj.get("country_of_citizenship").isJsonNull()) && !jsonObj.get("country_of_citizenship").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `country_of_citizenship` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country_of_citizenship").toString()));
      }
      if (!jsonObj.get("country_of_tax_residence").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `country_of_tax_residence` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country_of_tax_residence").toString()));
      }
      if (!jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
      if (!jsonObj.get("family_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `family_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("family_name").toString()));
      }
      if (!jsonObj.get("given_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `given_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("given_name").toString()));
      }
      if (!jsonObj.get("state").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `state` to be a primitive type in the JSON string but got `%s`", jsonObj.get("state").toString()));
      }
      if ((jsonObj.get("tax_id") != null && !jsonObj.get("tax_id").isJsonNull()) && !jsonObj.get("tax_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tax_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tax_id").toString()));
      }
      // validate the optional field `tax_id_type`
      if (jsonObj.get("tax_id_type") != null && !jsonObj.get("tax_id_type").isJsonNull()) {
        TaxIdType.validateJsonElement(jsonObj.get("tax_id_type"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CustodialAccountMinorIdentity.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CustodialAccountMinorIdentity' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CustodialAccountMinorIdentity> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CustodialAccountMinorIdentity.class));

       return (TypeAdapter<T>) new TypeAdapter<CustodialAccountMinorIdentity>() {
           @Override
           public void write(JsonWriter out, CustodialAccountMinorIdentity value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public CustodialAccountMinorIdentity read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             CustodialAccountMinorIdentity instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CustodialAccountMinorIdentity given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CustodialAccountMinorIdentity
   * @throws IOException if the JSON string is invalid with respect to CustodialAccountMinorIdentity
   */
  public static CustodialAccountMinorIdentity fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CustodialAccountMinorIdentity.class);
  }

  /**
   * Convert an instance of CustodialAccountMinorIdentity to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

