/*
 * Broker API
 * Open brokerage accounts, enable stock, options and crypto trading. Manage the ongoing user experience and brokerage customer lifecycle with the Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package markets.alpaca.client.openapi.broker.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Status:  * &#x60;incoming&#x60;: incoming amount  * &#x60;outgoing&#x60;: outgoing amount 
 */
@JsonAdapter(FundingWalletTransferDirection.Adapter.class)
public enum FundingWalletTransferDirection implements Serializable {
  
  INCOMING("incoming"),
  
  OUTGOING("outgoing");

  private String value;

  FundingWalletTransferDirection(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static FundingWalletTransferDirection fromValue(String value) {
    for (FundingWalletTransferDirection b : FundingWalletTransferDirection.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<FundingWalletTransferDirection> {
    @Override
    public void write(final JsonWriter jsonWriter, final FundingWalletTransferDirection enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public FundingWalletTransferDirection read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return FundingWalletTransferDirection.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    FundingWalletTransferDirection.fromValue(value);
  }
}

