/*
 * Broker API
 * Open brokerage accounts, enable stock, options and crypto trading. Manage the ongoing user experience and brokerage customer lifecycle with the Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package markets.alpaca.client.openapi.broker.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import markets.alpaca.client.openapi.broker.http.JSON;

/**
 * Represents an IPO offering lifecycle event delivered over the IPO events streaming API (&#x60;/v2/events/ipos&#x60;).  IPO events come in six &#x60;verb&#x60; types: - **&#x60;Offering&#x60;** - initial publication of an offering. The &#x60;payload&#x60; carries &#x60;name&#x60;, &#x60;available_to_order&#x60;, &#x60;ticker_symbol&#x60;, &#x60;min_price&#x60;, &#x60;max_price&#x60; (and optional &#x60;source&#x60;). - **&#x60;OfferingUpdate&#x60;** - update to a previously published offering. The &#x60;payload&#x60; shape is identical to &#x60;Offering&#x60;. - **&#x60;Prospectus&#x60;** - prospectus document is now available. The &#x60;payload&#x60; carries &#x60;prospectus_url&#x60; and &#x60;subject&#x60;. - **&#x60;SixtyMinMail&#x60;** - 60-minute pricing window has opened, no new orders accepted. The &#x60;payload&#x60; carries &#x60;sixty_minute_expiration_time&#x60; and &#x60;subject&#x60;. - **&#x60;Allocation&#x60;** - final allocation result for a specific account. The &#x60;payload&#x60; carries &#x60;cusip_id&#x60;, &#x60;final_price&#x60;, &#x60;allocated_shares&#x60;, &#x60;allocated_amount&#x60;, &#x60;subject&#x60;. **This is the only verb that is account-scoped**: &#x60;account_id&#x60; and &#x60;correspondent&#x60; are populated. - **&#x60;OfferingCancellation&#x60;** - offering was cancelled. **No &#x60;payload&#x60; is present.**  See the example payloads below for a concrete example per verb. 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class IPOEvent implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ACCOUNT_ID = "account_id";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ID)
  @javax.annotation.Nullable
  private UUID accountId;

  public static final String SERIALIZED_NAME_AT = "at";
  @SerializedName(SERIALIZED_NAME_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime at;

  public static final String SERIALIZED_NAME_CORRESPONDENT = "correspondent";
  @SerializedName(SERIALIZED_NAME_CORRESPONDENT)
  @javax.annotation.Nullable
  private String correspondent;

  public static final String SERIALIZED_NAME_EVENT_ID = "event_id";
  @SerializedName(SERIALIZED_NAME_EVENT_ID)
  @javax.annotation.Nonnull
  private String eventId;

  public static final String SERIALIZED_NAME_OFFERING_REFERENCE = "offering_reference";
  @SerializedName(SERIALIZED_NAME_OFFERING_REFERENCE)
  @javax.annotation.Nonnull
  private String offeringReference;

  public static final String SERIALIZED_NAME_PAYLOAD = "payload";
  @SerializedName(SERIALIZED_NAME_PAYLOAD)
  @javax.annotation.Nullable
  private Object payload;

  public static final String SERIALIZED_NAME_RECEIVED_AT = "received_at";
  @SerializedName(SERIALIZED_NAME_RECEIVED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime receivedAt;

  /**
   * The IPO event type. Determines the shape of &#x60;payload&#x60;.
   */
  @JsonAdapter(VerbEnum.Adapter.class)
  public enum VerbEnum {
    ALLOCATION("Allocation"),
    
    OFFERING("Offering"),
    
    OFFERING_UPDATE("OfferingUpdate"),
    
    PROSPECTUS("Prospectus"),
    
    SIXTY_MIN_MAIL("SixtyMinMail"),
    
    OFFERING_CANCELLATION("OfferingCancellation");

    private String value;

    VerbEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static VerbEnum fromValue(String value) {
      for (VerbEnum b : VerbEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<VerbEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final VerbEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public VerbEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return VerbEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      VerbEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_VERB = "verb";
  @SerializedName(SERIALIZED_NAME_VERB)
  @javax.annotation.Nonnull
  private VerbEnum verb;

  public IPOEvent() {
  }

  public IPOEvent accountId(@javax.annotation.Nullable UUID accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * The account this event applies to. Only populated for &#x60;Allocation&#x60; events; omitted for system-wide verbs (&#x60;Offering&#x60;, &#x60;OfferingUpdate&#x60;, &#x60;Prospectus&#x60;, &#x60;SixtyMinMail&#x60;, &#x60;OfferingCancellation&#x60;). 
   * @return accountId
   */
  @javax.annotation.Nullable
  public UUID getAccountId() {
    return accountId;
  }

  public void setAccountId(@javax.annotation.Nullable UUID accountId) {
    this.accountId = accountId;
  }


  public IPOEvent at(@javax.annotation.Nonnull OffsetDateTime at) {
    this.at = at;
    return this;
  }

  /**
   * Timestamp the event was emitted by the streaming service.
   * @return at
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getAt() {
    return at;
  }

  public void setAt(@javax.annotation.Nonnull OffsetDateTime at) {
    this.at = at;
  }


  public IPOEvent correspondent(@javax.annotation.Nullable String correspondent) {
    this.correspondent = correspondent;
    return this;
  }

  /**
   * The correspondent that owns the account. Only populated for &#x60;Allocation&#x60; events. 
   * @return correspondent
   */
  @javax.annotation.Nullable
  public String getCorrespondent() {
    return correspondent;
  }

  public void setCorrespondent(@javax.annotation.Nullable String correspondent) {
    this.correspondent = correspondent;
  }


  public IPOEvent eventId(@javax.annotation.Nonnull String eventId) {
    this.eventId = eventId;
    return this;
  }

  /**
   * Lexically sortable, monotonically increasing identifier for this event. Use this value with &#x60;since_id&#x60;/&#x60;until_id&#x60; to resume the stream from a known point.
   * @return eventId
   */
  @javax.annotation.Nonnull
  public String getEventId() {
    return eventId;
  }

  public void setEventId(@javax.annotation.Nonnull String eventId) {
    this.eventId = eventId;
  }


  public IPOEvent offeringReference(@javax.annotation.Nonnull String offeringReference) {
    this.offeringReference = offeringReference;
    return this;
  }

  /**
   * The IPO offering this event refers to. Use this value with &#x60;GET /v1/ipos/{offering_reference}&#x60; to fetch the full offering metadata. 
   * @return offeringReference
   */
  @javax.annotation.Nonnull
  public String getOfferingReference() {
    return offeringReference;
  }

  public void setOfferingReference(@javax.annotation.Nonnull String offeringReference) {
    this.offeringReference = offeringReference;
  }


  public IPOEvent payload(@javax.annotation.Nullable Object payload) {
    this.payload = payload;
    return this;
  }

  /**
   * Verb-specific payload. The shape varies by &#x60;verb&#x60; - see schema description and &#x60;components/examples&#x60; for the structure of each. **Omitted entirely for &#x60;OfferingCancellation&#x60;.** 
   * @return payload
   */
  @javax.annotation.Nullable
  public Object getPayload() {
    return payload;
  }

  public void setPayload(@javax.annotation.Nullable Object payload) {
    this.payload = payload;
  }


  public IPOEvent receivedAt(@javax.annotation.Nonnull OffsetDateTime receivedAt) {
    this.receivedAt = receivedAt;
    return this;
  }

  /**
   * Timestamp the upstream event was first received by Alpaca&#39;s IPO ingestion pipeline (before fanout).
   * @return receivedAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getReceivedAt() {
    return receivedAt;
  }

  public void setReceivedAt(@javax.annotation.Nonnull OffsetDateTime receivedAt) {
    this.receivedAt = receivedAt;
  }


  public IPOEvent verb(@javax.annotation.Nonnull VerbEnum verb) {
    this.verb = verb;
    return this;
  }

  /**
   * The IPO event type. Determines the shape of &#x60;payload&#x60;.
   * @return verb
   */
  @javax.annotation.Nonnull
  public VerbEnum getVerb() {
    return verb;
  }

  public void setVerb(@javax.annotation.Nonnull VerbEnum verb) {
    this.verb = verb;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the IPOEvent instance itself
   */
  public IPOEvent putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IPOEvent ipOEvent = (IPOEvent) o;
    return Objects.equals(this.accountId, ipOEvent.accountId) &&
        Objects.equals(this.at, ipOEvent.at) &&
        Objects.equals(this.correspondent, ipOEvent.correspondent) &&
        Objects.equals(this.eventId, ipOEvent.eventId) &&
        Objects.equals(this.offeringReference, ipOEvent.offeringReference) &&
        Objects.equals(this.payload, ipOEvent.payload) &&
        Objects.equals(this.receivedAt, ipOEvent.receivedAt) &&
        Objects.equals(this.verb, ipOEvent.verb)&&
        Objects.equals(this.additionalProperties, ipOEvent.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, at, correspondent, eventId, offeringReference, payload, receivedAt, verb, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IPOEvent {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    at: ").append(toIndentedString(at)).append("\n");
    sb.append("    correspondent: ").append(toIndentedString(correspondent)).append("\n");
    sb.append("    eventId: ").append(toIndentedString(eventId)).append("\n");
    sb.append("    offeringReference: ").append(toIndentedString(offeringReference)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("    receivedAt: ").append(toIndentedString(receivedAt)).append("\n");
    sb.append("    verb: ").append(toIndentedString(verb)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("account_id", "at", "correspondent", "event_id", "offering_reference", "payload", "received_at", "verb"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("at", "event_id", "offering_reference", "received_at", "verb"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to IPOEvent
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!IPOEvent.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in IPOEvent is not found in the empty JSON string", IPOEvent.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : IPOEvent.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("account_id") != null && !jsonObj.get("account_id").isJsonNull()) && !jsonObj.get("account_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `account_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("account_id").toString()));
      }
      if ((jsonObj.get("correspondent") != null && !jsonObj.get("correspondent").isJsonNull()) && !jsonObj.get("correspondent").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `correspondent` to be a primitive type in the JSON string but got `%s`", jsonObj.get("correspondent").toString()));
      }
      if (!jsonObj.get("event_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `event_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("event_id").toString()));
      }
      if (!jsonObj.get("offering_reference").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `offering_reference` to be a primitive type in the JSON string but got `%s`", jsonObj.get("offering_reference").toString()));
      }
      if (!jsonObj.get("verb").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `verb` to be a primitive type in the JSON string but got `%s`", jsonObj.get("verb").toString()));
      }
      // validate the required field `verb`
      VerbEnum.validateJsonElement(jsonObj.get("verb"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IPOEvent.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IPOEvent' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IPOEvent> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IPOEvent.class));

       return (TypeAdapter<T>) new TypeAdapter<IPOEvent>() {
           @Override
           public void write(JsonWriter out, IPOEvent value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public IPOEvent read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             IPOEvent instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of IPOEvent given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of IPOEvent
   * @throws IOException if the JSON string is invalid with respect to IPOEvent
   */
  public static IPOEvent fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IPOEvent.class);
  }

  /**
   * Convert an instance of IPOEvent to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

