/*
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Fixed income, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package markets.alpaca.client.openapi.data.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Controls which corporate actions are returned based on data quality.  - &#x60;complete&#x60; (default): exclude corporate actions that are still missing required   fields (for example, ex-date or CUSIP/ISIN) and have not yet been processed.   Already-processed corporate actions are always included, even if they would   otherwise be considered incomplete. - &#x60;all&#x60;: return matching corporate actions regardless of field completeness. 
 */
@JsonAdapter(DataQuality.Adapter.class)
public enum DataQuality implements Serializable {
  
  COMPLETE("complete"),
  
  ALL("all");

  private String value;

  DataQuality(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DataQuality fromValue(String value) {
    for (DataQuality b : DataQuality.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<DataQuality> {
    @Override
    public void write(final JsonWriter jsonWriter, final DataQuality enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public DataQuality read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return DataQuality.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    DataQuality.fromValue(value);
  }
}

