/*
 * Market Data API
 * Access real-time and historical market data for US equities, options, crypto, and foreign exchange data through the Alpaca REST and WebSocket APIs. There are APIs for Stock Pricing, Option Pricing, Crypto Pricing, Forex, Logos, Corporate Actions, Screener, and News. 
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package markets.alpaca.client.openapi.data.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import markets.alpaca.client.openapi.data.model.MarketType;
import markets.alpaca.client.openapi.data.model.Mover;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import markets.alpaca.client.openapi.data.http.JSON;

/**
 * Contains list of market movers.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class MoversResp implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_GAINERS = "gainers";
  @SerializedName(SERIALIZED_NAME_GAINERS)
  @javax.annotation.Nonnull
  private List<Mover> gainers = new ArrayList<>();

  public static final String SERIALIZED_NAME_LAST_UPDATED = "last_updated";
  @SerializedName(SERIALIZED_NAME_LAST_UPDATED)
  @javax.annotation.Nonnull
  private String lastUpdated;

  public static final String SERIALIZED_NAME_LOSERS = "losers";
  @SerializedName(SERIALIZED_NAME_LOSERS)
  @javax.annotation.Nonnull
  private List<Mover> losers = new ArrayList<>();

  public static final String SERIALIZED_NAME_MARKET_TYPE = "market_type";
  @SerializedName(SERIALIZED_NAME_MARKET_TYPE)
  @javax.annotation.Nonnull
  private MarketType marketType;

  public MoversResp() {
  }

  public MoversResp gainers(@javax.annotation.Nonnull List<Mover> gainers) {
    this.gainers = gainers;
    return this;
  }

  public MoversResp addGainersItem(Mover gainersItem) {
    if (this.gainers == null) {
      this.gainers = new ArrayList<>();
    }
    this.gainers.add(gainersItem);
    return this;
  }

  /**
   * List of top N gainers.
   * @return gainers
   */
  @javax.annotation.Nonnull
  public List<Mover> getGainers() {
    return gainers;
  }

  public void setGainers(@javax.annotation.Nonnull List<Mover> gainers) {
    this.gainers = gainers;
  }


  public MoversResp lastUpdated(@javax.annotation.Nonnull String lastUpdated) {
    this.lastUpdated = lastUpdated;
    return this;
  }

  /**
   * Time when the movers were last computed. Formatted as a RFC-3339 date-time with nanosecond precision. 
   * @return lastUpdated
   */
  @javax.annotation.Nonnull
  public String getLastUpdated() {
    return lastUpdated;
  }

  public void setLastUpdated(@javax.annotation.Nonnull String lastUpdated) {
    this.lastUpdated = lastUpdated;
  }


  public MoversResp losers(@javax.annotation.Nonnull List<Mover> losers) {
    this.losers = losers;
    return this;
  }

  public MoversResp addLosersItem(Mover losersItem) {
    if (this.losers == null) {
      this.losers = new ArrayList<>();
    }
    this.losers.add(losersItem);
    return this;
  }

  /**
   * List of top N losers.
   * @return losers
   */
  @javax.annotation.Nonnull
  public List<Mover> getLosers() {
    return losers;
  }

  public void setLosers(@javax.annotation.Nonnull List<Mover> losers) {
    this.losers = losers;
  }


  public MoversResp marketType(@javax.annotation.Nonnull MarketType marketType) {
    this.marketType = marketType;
    return this;
  }

  /**
   * Get marketType
   * @return marketType
   */
  @javax.annotation.Nonnull
  public MarketType getMarketType() {
    return marketType;
  }

  public void setMarketType(@javax.annotation.Nonnull MarketType marketType) {
    this.marketType = marketType;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the MoversResp instance itself
   */
  public MoversResp putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MoversResp moversResp = (MoversResp) o;
    return Objects.equals(this.gainers, moversResp.gainers) &&
        Objects.equals(this.lastUpdated, moversResp.lastUpdated) &&
        Objects.equals(this.losers, moversResp.losers) &&
        Objects.equals(this.marketType, moversResp.marketType)&&
        Objects.equals(this.additionalProperties, moversResp.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gainers, lastUpdated, losers, marketType, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MoversResp {\n");
    sb.append("    gainers: ").append(toIndentedString(gainers)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("    losers: ").append(toIndentedString(losers)).append("\n");
    sb.append("    marketType: ").append(toIndentedString(marketType)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("gainers", "last_updated", "losers", "market_type"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("gainers", "last_updated", "losers", "market_type"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MoversResp
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MoversResp.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in MoversResp is not found in the empty JSON string", MoversResp.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MoversResp.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("gainers") != null) {
        if (!jsonObj.get("gainers").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `gainers` to be an array in the JSON string but got `%s`", jsonObj.get("gainers").toString()));
        }
        JsonArray jsonArraygainers = jsonObj.getAsJsonArray("gainers");
        // validate the required field `gainers` (array)
        for (int i = 0; i < jsonArraygainers.size(); i++) {
          Mover.validateJsonElement(jsonArraygainers.get(i));
        }
      }
      if (!jsonObj.get("last_updated").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `last_updated` to be a primitive type in the JSON string but got `%s`", jsonObj.get("last_updated").toString()));
      }
      if (jsonObj.get("losers") != null) {
        if (!jsonObj.get("losers").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `losers` to be an array in the JSON string but got `%s`", jsonObj.get("losers").toString()));
        }
        JsonArray jsonArraylosers = jsonObj.getAsJsonArray("losers");
        // validate the required field `losers` (array)
        for (int i = 0; i < jsonArraylosers.size(); i++) {
          Mover.validateJsonElement(jsonArraylosers.get(i));
        }
      }
      // validate the required field `market_type`
      MarketType.validateJsonElement(jsonObj.get("market_type"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MoversResp.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MoversResp' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MoversResp> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MoversResp.class));

       return (TypeAdapter<T>) new TypeAdapter<MoversResp>() {
           @Override
           public void write(JsonWriter out, MoversResp value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonNull()) {
                     obj.add(entry.getKey(), JsonNull.INSTANCE);
                   } else if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public MoversResp read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             MoversResp instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MoversResp given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MoversResp
   * @throws IOException if the JSON string is invalid with respect to MoversResp
   */
  public static MoversResp fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MoversResp.class);
  }

  /**
   * Convert an instance of MoversResp to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

