name: Build

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  build:
    name: Gradle build (private specs)
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Checkout client
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Code checks
        run: ./gradlew spotlessCheck checkstyleMain checkstyleTest spotbugsMain

      - name: Build
        run: ./gradlew build

  public-spec-build:
    name: Gradle build (public specs)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout client
        uses: actions/checkout@v7

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Code checks
        run: ./gradlew spotlessCheck checkstyleMain checkstyleTest spotbugsMain

      - name: Build
        run: ./gradlew build
